/* HAHN & VO — Datenschicht (einzige Wahrheitsquelle).
   Erzeugt aus dem Live-Bestand von hahn-vo.de mit tools/build_data.py */
window.SITE = {
 "company": "Hahn & Vo OHG",
 "owners": "Hannes Hahn & Minh Vo",
 "email": "info@hahntime.com",
 "phone": "+49 176 8421 1760",
 "whatsappPhone": "+49 176 203 800 47",
 "whatsapp": "https://wa.me/4917620380047",
 "instagram": "https://www.instagram.com/hahn.vo/",
 "instagramHandle": "@hahn.vo",
 "tiktok": "https://www.tiktok.com/@hahn.vo",
 "showroom": "Garden Tower · 7. Etage, Neue Mainzer Straße 46–50, 60311 Frankfurt am Main",
 "legalAddress": "Luisenstraße 81, 63067 Offenbach am Main",
 "vatId": "DE453178178",
 "register": "HRA 43504",
 "whatsappChannel": "https://whatsapp.com/channel/0029VbAuiZnEawdspdIfjW1i",
 "youtube": "https://www.youtube.com/@hahn-vo"
};

window.PRODUCTS = [
 {
  "id": "p2162",
  "brand": "Sinn",
  "name": "Chronograph Vollkalender 38mm Weiß 77990 Automatik",
  "ref": "A-90358",
  "price": 2190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": "Gut",
  "year": null,
  "size": "38 mm",
  "material": "Edelstahl (Vergoldet)",
  "dial": "Weiß",
  "strap": "Leder (Aftermarket von Kaufmann)",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-2162",
  "desc": "Hier präsentieren wir die Sinn Chronograph Vollkalender. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p2162/0.jpg",
   "assets/products/p2162/1.jpg",
   "assets/products/p2162/2.jpg",
   "assets/products/p2162/3.jpg",
   "assets/products/p2162/4.jpg",
   "assets/products/p2162/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/sinn-chronograph-vollkalender-38mm-wei-77990-a-90358-automatik"
 },
 {
  "id": "p5069",
  "brand": "Tudor",
  "name": "Black Bay Bucherer Blue Automatik only watch",
  "ref": "79250BB",
  "price": 2790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "43 mm",
  "material": "Bronze",
  "dial": "Blau",
  "strap": "Textil",
  "movement": "Automatik (Manufakturwerk)",
  "sku": null,
  "code": "HV-5069",
  "desc": "Hier präsentieren wir die Tudor Black Bay Bucherer Blue Ref. 79250BB. Eine seltene Sonderedition, die exklusiv für Bucherer gefertigt wurde. Besonders charakteristisch sind das markante blaue Zifferblatt und die blaue Lünette. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5069/0.jpg",
   "assets/products/p5069/1.jpg",
   "assets/products/p5069/2.jpg",
   "assets/products/p5069/3.jpg",
   "assets/products/p5069/4.jpg",
   "assets/products/p5069/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-black-bay-bucherer-blue-79250bb-automatik-only-watch"
 },
 {
  "id": "p4846",
  "brand": "Rolex",
  "name": "Datejust 36 seltenes Zifferblatt mit Diamanten",
  "ref": "116234",
  "price": 7990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2014",
  "size": "36 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Edelstahl",
  "movement": "Rolex 3135",
  "sku": null,
  "code": "HV-4846",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 aus dem Jahr 2014 im Full Set. Die Rolex verfügt über ein besonderes Jubilee dial mit diamantbesetzten Ziffern bei 6 und 9. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p4846/0.jpg",
   "assets/products/p4846/1.jpg",
   "assets/products/p4846/2.jpg",
   "assets/products/p4846/3.jpg",
   "assets/products/p4846/4.jpg",
   "assets/products/p4846/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-seltenes-zb-mit-diamanten-116234-full-set-2014"
 },
 {
  "id": "p4808",
  "brand": "Patek Philippe",
  "name": "Twenty~4 Grau Damenuhr",
  "ref": "4910/10A",
  "price": 8990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": "Gut",
  "year": "2010",
  "size": "25,1 x 30 mm",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": "Quarz E15",
  "sku": null,
  "code": "HV-4808",
  "desc": "Hier präsentieren wir die Patek Philippe Twenty~4 aus dem Jahr 2010 mit Original Zetifikat & Reisebox. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p4808/0.jpg",
   "assets/products/p4808/1.jpg",
   "assets/products/p4808/2.jpg",
   "assets/products/p4808/3.jpg",
   "assets/products/p4808/4.jpg",
   "assets/products/p4808/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/patek-philippe-twenty4-grau-491010a-damenuhr-2010"
 },
 {
  "id": "p3771",
  "brand": "IWC",
  "name": "Schaffhausen Portofino Automatic 40 Zifferblatt silber",
  "ref": null,
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut ",
  "year": "2021 (Garantie bei IWC bis 2029)",
  "size": "40 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-3771",
  "desc": "Hier präsentieren wir die IWC Portofino Automatic 40 (only watch), jedoch mit Garantie bei IWC bis zum Jahr 07/2029. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p3771/0.jpg",
   "assets/products/p3771/1.jpg",
   "assets/products/p3771/2.jpg",
   "assets/products/p3771/3.jpg",
   "assets/products/p3771/4.jpg",
   "assets/products/p3771/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-schaffhausen-portofino-automatic-40-zb-silber-jahr-2021"
 },
 {
  "id": "p2446",
  "brand": "Omega",
  "name": "Seamaster Diver 300 M Zifferblatt Blau Garantiekarte",
  "ref": "212.30.41.20.03.001",
  "price": 3090,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Garantiekarte, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2009 (Ungefähre Angabe)",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-2446",
  "desc": "Hier präsentieren wir die Omega Diver 300 Blue mit Original Omega Garantiekarte. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p2446/0.jpg",
   "assets/products/p2446/1.jpg",
   "assets/products/p2446/2.jpg",
   "assets/products/p2446/3.jpg",
   "assets/products/p2446/4.jpg",
   "assets/products/p2446/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-diver-300-m-21230412003001-zb-blau-garantiekarte"
 },
 {
  "id": "p1226",
  "brand": "Breitling",
  "name": "Superocean Heritage 46",
  "ref": "A1331212/BF78",
  "price": 3790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2018",
  "size": null,
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-1226",
  "desc": "Hier präsentieren wir die Breitling Superocean Heritage Chronograph 46 mm im Full Set aus dem Jahr 2018. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1226/0.jpg",
   "assets/products/p1226/1.jpg",
   "assets/products/p1226/2.jpg",
   "assets/products/p1226/3.jpg",
   "assets/products/p1226/4.jpg",
   "assets/products/p1226/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-superocean-heritage-46-a1331212bf78-full-set-jahr-2018"
 },
 {
  "id": "p9320",
  "brand": "TAG Heuer",
  "name": "Carrera Chronograph (2020)",
  "ref": "CBN2A1B.BA0643",
  "price": 2790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set",
  "rating": "Sehr gut",
  "year": "2020",
  "size": "44 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-9320",
  "desc": "Hier präsentieren wir die TAG Heuer Carerra Chronograph aus dem Jahr 2020 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p9320/0.jpg",
   "assets/products/p9320/1.jpg",
   "assets/products/p9320/2.jpg",
   "assets/products/p9320/3.jpg",
   "assets/products/p9320/4.jpg",
   "assets/products/p9320/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-chronograph-ref-cbn2a1bba0643-full-set-2020"
 },
 {
  "id": "p9311",
  "brand": "Sinn",
  "name": "Spezialuhren Chronograph 936",
  "ref": null,
  "price": 2490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2024",
  "size": "43 mm",
  "material": "Stahl",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-9311",
  "desc": "Hier präsentieren wir die Sinn 936 im Full Set aus dem Jahre 2024. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p9311/0.jpg",
   "assets/products/p9311/1.jpg",
   "assets/products/p9311/2.jpg",
   "assets/products/p9311/3.jpg",
   "assets/products/p9311/4.jpg",
   "assets/products/p9311/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/sinn-spezialuhren-chronograph-936-full-set-jahr-2024"
 },
 {
  "id": "p9290",
  "brand": "Breitling",
  "name": "Superocean Heritage 42",
  "ref": "A1732124/BA61",
  "price": 3250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2016",
  "size": null,
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-9290",
  "desc": "Hier präsentieren wir die Breitling Superocean Heritage 42 im Full Set aus dem Jahr 2016. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p9290/0.jpg",
   "assets/products/p9290/1.jpg",
   "assets/products/p9290/2.jpg",
   "assets/products/p9290/3.jpg",
   "assets/products/p9290/4.jpg",
   "assets/products/p9290/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-superocean-heritage-42-a1732124ba61-full-set-jahr-2016"
 },
 {
  "id": "p7474",
  "brand": "IWC",
  "name": "Schaffhausen Fliegeruhr MK18 Laureus Garantiekarte",
  "ref": "IW324703",
  "price": 4390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Garantiekarte",
  "rating": "Sehr gut",
  "year": "2018",
  "size": "41 mm",
  "material": "Keramik",
  "dial": "Blau",
  "strap": "Textil, Leder Inlay",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-7474",
  "desc": "Wir präsentieren die IWC Pilot's Watch Mark XVIII Laureus Edition Ref. IW324703. Eine auf nur 1.500 Exemplare weltweit limitierte Sonderedition für die Laureus Foundation. Unsere Bilder zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p7474/0.jpg",
   "assets/products/p7474/1.jpg",
   "assets/products/p7474/2.jpg",
   "assets/products/p7474/3.jpg",
   "assets/products/p7474/4.jpg",
   "assets/products/p7474/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-schaffhausen-fliegeruhr-mk18-iw324703-laureus-garantiekarte"
 },
 {
  "id": "p1799",
  "brand": "Tudor",
  "name": "Heritage Chronograph 42mm Zifferblatt Schwarz",
  "ref": "70330N",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Sehr gut",
  "year": "2011",
  "size": "42 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatk",
  "sku": null,
  "code": "HV-1799",
  "desc": "Hier präsentieren wir die Tudor Heritage Chronograph aus dem Jahr 2011 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1799/0.jpg",
   "assets/products/p1799/1.jpg",
   "assets/products/p1799/2.jpg",
   "assets/products/p1799/3.jpg",
   "assets/products/p1799/4.jpg",
   "assets/products/p1799/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-heritage-chronograph-42mm-zb-schwarz-70330n-full-set-2011"
 },
 {
  "id": "p9177",
  "brand": "Rolex",
  "name": "GMT Master II Left Hand Sprite",
  "ref": "126720VTNR",
  "price": 14400,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Sehr gut",
  "year": "2023",
  "size": "40 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-9177",
  "desc": "Hier präsentieren wir die Rolex GMT Master II aus dem Jahr 2023 im Full Set. Die Rolex GMT-Master II Left Hand zeichnet sich durch ihre außergewöhnliche Anordnung der Krone auf der linken Gehäuseseite aus. In Kombination mit der grün-schwarzen Lünette zählt sie zu den begehrtesten Rolex-Modellen. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p9177/0.jpg",
   "assets/products/p9177/1.jpg",
   "assets/products/p9177/2.jpg",
   "assets/products/p9177/3.jpg",
   "assets/products/p9177/4.jpg",
   "assets/products/p9177/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-gmt-master-ii-left-hand-sprite-126720vtnr-2023-full-set"
 },
 {
  "id": "p6059",
  "brand": "Breitling",
  "name": "Avenger Chronograph Blau 45mm",
  "ref": "A13317101C1A1",
  "price": 3390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2020",
  "size": "45 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-6059",
  "desc": "Hier präsentieren wir die Breitling Avenger Chronograph 45 aus dem Jahr 2020 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p6059/0.jpg",
   "assets/products/p6059/1.jpg",
   "assets/products/p6059/2.jpg",
   "assets/products/p6059/3.jpg",
   "assets/products/p6059/4.jpg",
   "assets/products/p6059/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-chronograph-blau-45mm-a13317101c1a1-full-set"
 },
 {
  "id": "p5825",
  "brand": "A. Lange & Söhne",
  "name": "Saxonia Ultra Thin 37 mm Weißgold",
  "ref": "201.027",
  "price": 15400,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "37 mm",
  "material": "Weißgold",
  "dial": "Weiß",
  "strap": "Leder (orig. L&S Armband sehr guter Zustand)",
  "movement": "Handaufzug (Kal. L.093.1)",
  "sku": null,
  "code": "HV-5825",
  "desc": "Hier präsentieren wir die elegante A. Lange & Söhne Saxonia 37 mm Ref. 201.027. Eine Ikone deutscher Uhrmacherkunst. Zum Lieferumfang gehört zudem ein hochwertiges L&S Travel Pouch, das diese außergewöhnliche Uhr stilvoll ergänzt. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5825/0.jpg",
   "assets/products/p5825/1.jpg",
   "assets/products/p5825/2.jpg",
   "assets/products/p5825/3.jpg",
   "assets/products/p5825/4.jpg",
   "assets/products/p5825/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/a-lange-sohne-saxonia-201027-ultra-thin-37-mm-weigold"
 },
 {
  "id": "p5085",
  "brand": "A. Lange & Söhne",
  "name": "Glashütte Taschenuhr Kaliber 43 L&S",
  "ref": null,
  "price": 3490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Gut",
  "year": "1907",
  "size": "53 mm",
  "material": "Silber",
  "dial": "Weiß",
  "strap": null,
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-5085",
  "desc": "Hier präsentieren wir eine Lange & Söhne Taschenuhr mit L&S Zertifikat und Archivauszug von Glashütte, sowie die original Uhrenbox. Ein wahres Sammlerstück. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5085/0.jpg",
   "assets/products/p5085/1.jpg",
   "assets/products/p5085/2.jpg",
   "assets/products/p5085/3.jpg",
   "assets/products/p5085/4.jpg",
   "assets/products/p5085/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/a-lange-sohne-glashutte-taschenuhr-kaliber-43-ls-uhrenbox"
 },
 {
  "id": "p5044",
  "brand": "Breitling",
  "name": "Chronomat Colt Zifferblatt Blau + Kautschukband",
  "ref": "A17388",
  "price": 2290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2019",
  "size": "44 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl + Kautschukband",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-5044",
  "desc": "Hier präsentieren wir den Breitling Chronomat Colt aus dem Jahr 2019 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5044/0.jpg",
   "assets/products/p5044/1.jpg",
   "assets/products/p5044/2.jpg",
   "assets/products/p5044/3.jpg",
   "assets/products/p5044/4.jpg",
   "assets/products/p5044/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-chronomat-colt-a17388-zb-blau-full-set-kautschukband"
 },
 {
  "id": "p5038",
  "brand": "IWC",
  "name": "Portugieser Yacht Club Chronograph",
  "ref": "IW390502",
  "price": 5990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2017",
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder / Kautschuk Inlay",
  "movement": "Automatik (Manufakturwerk mit Flybackfunktion)",
  "sku": null,
  "code": "HV-5038",
  "desc": "Hier präsentieren wir den IWC Portugieser Yacht Club Chrono im Full Set mit Flyback Funktion. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5038/0.jpg",
   "assets/products/p5038/1.jpg",
   "assets/products/p5038/2.jpg",
   "assets/products/p5038/3.jpg",
   "assets/products/p5038/4.jpg",
   "assets/products/p5038/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portugieser-yacht-club-chronograph-iw390502-full-set"
 },
 {
  "id": "p3766",
  "brand": "Panerai",
  "name": "Radiomir Handaufzug",
  "ref": "PAM01385",
  "price": 5450,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2024 (Garantie bei Panerai bis 2032)",
  "size": "44 mm",
  "material": "Edelstahl",
  "dial": "Hellbraun",
  "strap": "Leder",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-3766",
  "desc": "Hier präsentieren wir die Panerai Radiomir PAM01385 im Full Set aus dem Jahr 2024. Diese Panerai hat eine Restgarantie bis 2032. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p3766/0.jpg",
   "assets/products/p3766/1.jpg",
   "assets/products/p3766/2.jpg",
   "assets/products/p3766/3.jpg",
   "assets/products/p3766/4.jpg",
   "assets/products/p3766/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/panerai-radiomir-pam01385-handaufzug-full-set-jahr-2024"
 },
 {
  "id": "p3762",
  "brand": "Rolex",
  "name": "Oyster Perpetual Date 34",
  "ref": "15200",
  "price": 5290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2000",
  "size": "34 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-3762",
  "desc": "Hier präsentieren wir die Rolex Oyster Perpetual Date 15200 im Full Set. Die Oyster Perpetual Date 34 hatte eine Revision im Jahre 2021 bei Rolex gehabt. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p3762/0.jpg",
   "assets/products/p3762/1.jpg",
   "assets/products/p3762/2.jpg",
   "assets/products/p3762/3.jpg",
   "assets/products/p3762/4.jpg",
   "assets/products/p3762/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-oyster-perpetual-date-34-ref-15200-full-set-jahr-2000"
 },
 {
  "id": "p4284",
  "brand": "IWC",
  "name": "Fliegeruhr Chronograph Bronze Garantiekarte",
  "ref": "IW387902",
  "price": 5390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2020",
  "size": "41",
  "material": "Bronze",
  "dial": "Grün",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-4284",
  "desc": "Hier präsentieren wir die IWC Fliegeruhr Chronograph aus dem Jahr 2020 mit IWC Zertifikat. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p4284/0.jpg",
   "assets/products/p4284/1.jpg",
   "assets/products/p4284/2.jpg",
   "assets/products/p4284/3.jpg",
   "assets/products/p4284/4.jpg",
   "assets/products/p4284/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-fliegeruhr-chronograph-bronze-iw387902-garantiekarte-2020"
 },
 {
  "id": "p4267",
  "brand": "Cartier",
  "name": "Santos Galbee Stahl/Gold 24x35 Quarz",
  "ref": "119902",
  "price": 4480,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Echtheitszertifikat",
  "rating": "Gut",
  "year": null,
  "size": "24 x 35",
  "material": "Edelstahl/Gelbgold",
  "dial": "Weiß",
  "strap": "Edelstahl/Gelbgold",
  "movement": "Quarz",
  "sku": null,
  "code": "HV-4267",
  "desc": "Hier präsentieren wir die Cartier Santos Galbee in Edelstahl/Gelbgold. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p4267/0.jpg",
   "assets/products/p4267/1.jpg",
   "assets/products/p4267/2.jpg",
   "assets/products/p4267/3.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/cartier-santos-galbee-119902-stahlgold-24x35-quarz"
 },
 {
  "id": "p7015",
  "brand": "Sinn",
  "name": "203 Ti Chronograph Automatik Sinn-Rechnung + 1x Titanband Zifferblatt 303 Yukon Kristall",
  "ref": null,
  "price": 2390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Gut",
  "year": "1999",
  "size": "41 mm",
  "material": "Titan",
  "dial": "Blau",
  "strap": "Titan",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-7015",
  "desc": "Hier präsentieren wir euch die Sinn 203 Chronograph mit Titangehäuse und Titanarmband. Die originale Sinn-Rechnung aus dem Jahr 1999 ist ebenfalls vorhanden. Zusätzlich wurde die Lünette im Januar 2023 direkt bei Sinn erneuert, der entsprechende Servicenachweis liegt bei. Zum Lieferumfang gehören außerdem ein 2. originales Titanarmband sowie alle beim Lünettenwechsel ausgebauten Originalteile.",
  "images": [
   "assets/products/p7015/0.jpg",
   "assets/products/p7015/1.jpg",
   "assets/products/p7015/2.jpg",
   "assets/products/p7015/3.jpg",
   "assets/products/p7015/4.jpg",
   "assets/products/p7015/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/sinn-203-ti-chronograph-automatik-sinn-rechnung-1x-titanband-zb-303-yukon-kristall"
 },
 {
  "id": "p3734",
  "brand": "Vacheron Constantin",
  "name": "Overseas Chronograph Zifferblatt Weiß",
  "ref": "49150",
  "price": 16490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "42 mm",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-3734",
  "desc": "Hier präsentieren wir den Vacheron Constantin Overseas Chronograph mit orig. VC Uhrenbox. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p3734/0.jpg",
   "assets/products/p3734/1.jpg",
   "assets/products/p3734/2.jpg",
   "assets/products/p3734/3.jpg",
   "assets/products/p3734/4.jpg",
   "assets/products/p3734/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/vacheron-constantin-overseas-chronograph-ref-49150-box-zb-wei"
 },
 {
  "id": "p5556",
  "brand": "IWC",
  "name": "Big Pilot Big Date 150 Years Zifferblatt blau",
  "ref": "IW510503",
  "price": 13950,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Neuwertig & ungetragen",
  "year": "Dezember 2019",
  "size": "46 mm",
  "material": "Edelstahl",
  "dial": "Blau Emaille Look)",
  "strap": "Leder",
  "movement": "Handaufzug (8x Tage Gangreserve)",
  "sku": null,
  "code": "HV-5556",
  "desc": "Hier präsentieren wir die IWC Big Pilot Big Date 150 Years Edition. Eine streng limitierte Big Pilot zum 150 jährigen Jubiläum von IWC Schaffhausen. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5556/0.jpg",
   "assets/products/p5556/1.jpg",
   "assets/products/p5556/2.jpg",
   "assets/products/p5556/3.jpg",
   "assets/products/p5556/4.jpg",
   "assets/products/p5556/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-big-pilot-big-date-150-years-full-set-iw510503-zb-blau-neu"
 },
 {
  "id": "p5555",
  "brand": "IWC",
  "name": "Big Pilot Big Date 150 Years Zifferblatt weiß",
  "ref": "IW510504",
  "price": 13950,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "Dezember 2018",
  "size": "46 mm",
  "material": "Edelstahl",
  "dial": "Weiß (Emaille Look)",
  "strap": "Leder",
  "movement": "Handaufzug (8x Tage Gangreserve)",
  "sku": null,
  "code": "HV-5555",
  "desc": "Hier präsentieren wir die IWC Big Pilot Big Date 150 Years Edition. Eine streng limitierte Big Pilot zum 150 jährigen Jubiläum von IWC Schaffhausen. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p5555/0.jpg",
   "assets/products/p5555/1.jpg",
   "assets/products/p5555/2.jpg",
   "assets/products/p5555/3.jpg",
   "assets/products/p5555/4.jpg",
   "assets/products/p5555/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-big-pilot-big-date-150-years-full-set-iw510504-zb-wei"
 },
 {
  "id": "p1237",
  "brand": "Breitling",
  "name": "Superocean 44 Automatik",
  "ref": "A17367D71B1A1",
  "price": 2590,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Befriedigend",
  "year": "2020",
  "size": "44",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl (starke Gebrauchspuren, siehe Bilder)",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-1237",
  "desc": "Hier präsentieren wir die Breitling Superocean aus dem Jahr 2020 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1237/0.jpg",
   "assets/products/p1237/1.jpg",
   "assets/products/p1237/2.jpg",
   "assets/products/p1237/3.jpg",
   "assets/products/p1237/4.jpg",
   "assets/products/p1237/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-superocean-44-automatik-a17367d71b1a1-full-set-2020"
 },
 {
  "id": "p1218",
  "brand": "Panerai",
  "name": "Radiomir Handaufzug 47mm",
  "ref": "PAM00662",
  "price": 5490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Sehr gut",
  "year": "2016",
  "size": "47 mm",
  "material": "Edelstahl",
  "dial": "Braun",
  "strap": "Kautschuk",
  "movement": "P. 3000 Handaufzug",
  "sku": null,
  "code": "HV-1218",
  "desc": "Hier präsentieren wir die Panerai Radiomir 1940 aus dem Jahr 2016 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1218/0.jpg",
   "assets/products/p1218/1.jpg",
   "assets/products/p1218/2.jpg",
   "assets/products/p1218/3.jpg",
   "assets/products/p1218/4.jpg",
   "assets/products/p1218/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/panerai-radiomir-1940-handaufzug-47mm-pam00662-full-set-2016"
 },
 {
  "id": "p1157",
  "brand": "Cartier",
  "name": "Cle de Cartier Automatik 40mm",
  "ref": "WSCL0018",
  "price": 3690,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2019",
  "size": "40 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-1157",
  "desc": "Hier präsentieren wir die Cartier Cle de Cartier aus dem Jahr 2019 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1157/0.jpg",
   "assets/products/p1157/1.jpg",
   "assets/products/p1157/2.jpg",
   "assets/products/p1157/3.jpg",
   "assets/products/p1157/4.jpg",
   "assets/products/p1157/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/cartier-cle-de-cartier-automatik-wscl0018-40mm-2019-full-set"
 },
 {
  "id": "p1154",
  "brand": "Bvlgari",
  "name": "Octo Solotempo Automatik 41mm Zifferblatt Schwarz",
  "ref": "101964",
  "price": 4690,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Box, Echtheitszertifikat",
  "rating": "Gut",
  "year": "2015",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-1154",
  "desc": "Hier präsentieren wir die Bulgari Octo Solotempo aus dem Jahr 2015. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p1154/0.jpg",
   "assets/products/p1154/1.jpg",
   "assets/products/p1154/2.jpg",
   "assets/products/p1154/3.jpg",
   "assets/products/p1154/4.jpg",
   "assets/products/p1154/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/bulgari-octo-solotempo-automatik-101964-41mm-zb-schwarz-2015"
 },
 {
  "id": "p9012",
  "brand": "IWC",
  "name": "Ingenieur Chronograph Automatik 42mm",
  "ref": "IW380701",
  "price": 4890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": "Sehr gut",
  "year": "2016",
  "size": "42 mm",
  "material": "Titan",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-9012",
  "desc": "Hier präsentieren wir die IWC Ingenieur Chronograph aus dem Jahr 2016 in Titan. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p9012/0.jpg",
   "assets/products/p9012/1.jpg",
   "assets/products/p9012/2.jpg",
   "assets/products/p9012/3.jpg",
   "assets/products/p9012/4.jpg",
   "assets/products/p9012/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-ingenieur-chronograph-automatik-iw380701-42mm-2016"
 },
 {
  "id": "p462",
  "brand": "MB&F",
  "name": "Legacy Machine Split Escapement Titan",
  "ref": "04.TR.LB",
  "price": 109900,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set",
  "rating": "Sehr gut (wie neu)",
  "year": "2024",
  "size": "44 mm",
  "material": "Titan",
  "dial": "Blau",
  "strap": "Kautschukband",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-462",
  "desc": "Hier präsentieren wir die MB&F Legacy Machine Split Escapement aus dem Jahr 2024 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p462/0.jpg",
   "assets/products/p462/1.jpg",
   "assets/products/p462/2.jpg",
   "assets/products/p462/3.jpg",
   "assets/products/p462/4.jpg",
   "assets/products/p462/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/mbf-legacy-machine-split-escapement-titan-04trlb-full-set-2024"
 },
 {
  "id": "p458",
  "brand": "Rolex",
  "name": "Datejust 36 Zifferblatt blau Jubilee Automatik",
  "ref": "126200",
  "price": 9490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Neuwertig & ungetragen",
  "year": "2022",
  "size": "36 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-458",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 neuwertig & ungetragen aus dem Jahr 2022 im Full Set Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p458/0.jpg",
   "assets/products/p458/1.jpg",
   "assets/products/p458/2.jpg",
   "assets/products/p458/3.jpg",
   "assets/products/p458/4.jpg",
   "assets/products/p458/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-zb-blau-126200-jubilee-automatik-neu-jahr-2022"
 },
 {
  "id": "p454",
  "brand": "IWC",
  "name": "Big Pilot Top Gun Keramik 46mm",
  "ref": "IW502001",
  "price": 7790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2017",
  "size": "46 mm",
  "material": "Keramik",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-454",
  "desc": "Hier präsentieren wir die IWC Big Pilot Top Gun aus dem Jahr 2017 im Full Set.",
  "images": [
   "assets/products/p454/0.jpg",
   "assets/products/p454/1.jpg",
   "assets/products/p454/2.jpg",
   "assets/products/p454/3.jpg",
   "assets/products/p454/4.jpg",
   "assets/products/p454/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-big-pilot-top-gun-keramik-46mm-iw502001-full-set-2017"
 },
 {
  "id": "p450",
  "brand": "IWC",
  "name": "Portugieser Handaufzug",
  "ref": "IW545405",
  "price": 4190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Box, Garantiekarte",
  "rating": "Sehr gut",
  "year": null,
  "size": "44 mm",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-450",
  "desc": "Hier präsentieren wir die IWC Portugieser Handaufzug mit Box und Service-Garantiekarte. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p450/0.jpg",
   "assets/products/p450/1.jpg",
   "assets/products/p450/2.jpg",
   "assets/products/p450/3.jpg",
   "assets/products/p450/4.jpg",
   "assets/products/p450/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portugieser-handaufzug-iw545405-box-service-garantiekarte"
 },
 {
  "id": "p446",
  "brand": "Jaeger-LeCoultre",
  "name": "Reverso Handaufzug 40.1mm",
  "ref": null,
  "price": 6290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set",
  "rating": "Gut",
  "year": "2019",
  "size": "40.1 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-446",
  "desc": "Hier präsentieren wir die Jaeger Le Coultre Reverso aus dem Jahr 2019 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p446/0.jpg",
   "assets/products/p446/1.jpg",
   "assets/products/p446/2.jpg",
   "assets/products/p446/3.jpg",
   "assets/products/p446/4.jpg",
   "assets/products/p446/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/jaeger-le-coultre-reverso-handaufzug-401mm-2019-full-set"
 },
 {
  "id": "p441",
  "brand": "Longines",
  "name": "Saint-Imier Chronograph 41mm",
  "ref": "L2.752.4.72.6",
  "price": 1850,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-441",
  "desc": "Hier präsentieren wir die Rolex Longines Saint-Imier Chronograph. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p441/0.jpg",
   "assets/products/p441/1.jpg",
   "assets/products/p441/2.jpg",
   "assets/products/p441/3.jpg",
   "assets/products/p441/4.jpg",
   "assets/products/p441/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/longines-saint-imier-chronograph-41mm-l27524726"
 },
 {
  "id": "p440",
  "brand": "Breitling",
  "name": "Avenger Chronograph",
  "ref": "A13385101C1A1",
  "price": 3390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2021",
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-440",
  "desc": "Hier präsentieren wir die Breitling Avenger Chronograph aus dem Jahr 2021 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p440/0.jpg",
   "assets/products/p440/1.jpg",
   "assets/products/p440/2.jpg",
   "assets/products/p440/3.jpg",
   "assets/products/p440/4.jpg",
   "assets/products/p440/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-chronograph-a13385101c1a1-aus-2021-im-full-set"
 },
 {
  "id": "p435",
  "brand": "Rolex",
  "name": "Oyster Perpetual 34 mm Med Blue",
  "ref": "124200",
  "price": 7490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Neuwertig & Ungetragen",
  "year": "05/2026",
  "size": "34 mm",
  "material": "Edelstahl 904L",
  "dial": "Blau",
  "strap": "Edelstahl 904L",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-435",
  "desc": "Hier präsentieren wir die Rolex Oyster Perpetual 34 aus dem Jahr 2026 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p435/0.jpg",
   "assets/products/p435/1.jpg",
   "assets/products/p435/2.jpg",
   "assets/products/p435/3.jpg",
   "assets/products/p435/4.jpg",
   "assets/products/p435/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-oyster-perpetual-34-mm-124200-med-blue-2026-im-full-set"
 },
 {
  "id": "p434",
  "brand": "Nomos",
  "name": "Ludwig 34mm 205 Handaufzug",
  "ref": null,
  "price": 1190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2011",
  "size": "34 mm",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder (stark gebraucht)",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-434",
  "desc": "Hier präsentieren wir die Nomos Luwdwig aus dem Jahr 2011 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p434/0.jpg",
   "assets/products/p434/1.jpg",
   "assets/products/p434/2.jpg",
   "assets/products/p434/3.jpg",
   "assets/products/p434/4.jpg",
   "assets/products/p434/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/nomos-ludwig-34mm-205-handaufzug-aus-2011-im-full-set"
 },
 {
  "id": "p427",
  "brand": "Tudor",
  "name": "Royal 34 mm",
  "ref": "28400",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2021",
  "size": "34 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-427",
  "desc": "Hier präsentieren wir die Tudor Royal 34 aus dem Jahr 2021 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p427/0.jpg",
   "assets/products/p427/1.jpg",
   "assets/products/p427/2.jpg",
   "assets/products/p427/3.jpg",
   "assets/products/p427/4.jpg",
   "assets/products/p427/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-royal-34-mm-ref-28400-aus-2021-im-full-set"
 },
 {
  "id": "p426",
  "brand": "Tudor",
  "name": "Black Bay 36 St/GG",
  "ref": "79503",
  "price": 3390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2022",
  "size": "36 mm",
  "material": "Edelstahl/Gelbgold",
  "dial": "Schwarz",
  "strap": "Edelstahl/Gelbgold",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-426",
  "desc": "Hier präsentieren wir die Tudor Black Bay Stahl/Gold aus dem Jahr 2022 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p426/0.jpg",
   "assets/products/p426/1.jpg",
   "assets/products/p426/2.jpg",
   "assets/products/p426/3.jpg",
   "assets/products/p426/4.jpg",
   "assets/products/p426/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-black-bay-36-stgg-79503-aus-2022-im-full-set"
 },
 {
  "id": "p420",
  "brand": "IWC",
  "name": "Portofino 8 days Blau",
  "ref": "IW510106",
  "price": 5190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2015",
  "size": "45 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Leder",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-420",
  "desc": "Hier präsentieren wir die IWC Portofino 8 Days aus dem Jahr 2015 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p420/0.jpg",
   "assets/products/p420/1.jpg",
   "assets/products/p420/2.jpg",
   "assets/products/p420/3.jpg",
   "assets/products/p420/4.jpg",
   "assets/products/p420/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portofino-8-days-blau-iw510106-aus-2015-im-full-set"
 },
 {
  "id": "p415",
  "brand": "Breitling",
  "name": "Navitimer B01 Chronograph",
  "ref": "AB0121211C1A1",
  "price": 5550,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2018",
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik (B01 Manufakturwerk)",
  "sku": null,
  "code": "HV-415",
  "desc": "Hier präsentieren wir die Breitling Navitimer B01 Chronograph im Full Set mit frischer Garantie (April 2026). Der aktuelle Breitling-Listenpreis liegt bei 9.350 Euro. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p415/0.jpg",
   "assets/products/p415/1.jpg",
   "assets/products/p415/2.jpg",
   "assets/products/p415/3.jpg",
   "assets/products/p415/4.jpg",
   "assets/products/p415/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-navitimer-b01-chronograph-ab0121211c1a1-full-set-service-april-2026"
 },
 {
  "id": "p413",
  "brand": "Tudor",
  "name": "Black Bay Heritage 41 Lünette rot",
  "ref": "79230R-0003",
  "price": 2550,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-413",
  "desc": "Hier präsentieren wir die Tudor Black Bay Heritage 41. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p413/0.jpg",
   "assets/products/p413/1.jpg",
   "assets/products/p413/2.jpg",
   "assets/products/p413/3.jpg",
   "assets/products/p413/4.jpg",
   "assets/products/p413/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--tudor-black-bay-heritage-41-lnette-rot-79230r-0003-tudor-box-7gg"
 },
 {
  "id": "p412",
  "brand": "Breitling",
  "name": "Avenger II GMT Automatik Lederband Breitling",
  "ref": "A32390",
  "price": 2250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-412",
  "desc": "Hier kommt die Breitling Avenger II GMT. Für alle, die nicht nur eine, sondern gleich zwei Zeitzonen im Griff haben wollen. Natürlich inklusive originaler Box, damit sie sich auch nach dem Flug stilvoll ausruhen kann. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p412/0.jpg",
   "assets/products/p412/1.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-ii-gmt-automatik-a32390-lederband-breitling-box"
 },
 {
  "id": "p408",
  "brand": "Baume & Mercier",
  "name": "Hampton aus 18K Weißgold",
  "ref": "MV045226",
  "price": 3490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Garantiekarte",
  "rating": "Sehr gut Gehäusedurchmesser: 26 x 40 mm Gehäusematerial: Wei",
  "year": null,
  "size": "26 x 40 mm Gehäusematerial: Weißgold Armbandmaterial: Leder",
  "material": "Weißgold Armbandmaterial: Leder Armbandfarbe: Blau Zifferbla",
  "dial": "Weiß Referenznummer: MV045226 Uhrwerk: Quarz Originale Baume",
  "strap": "Leder Armbandfarbe: Blau Zifferblattfarbe: Weiß Referenznumm",
  "movement": "Quarz Originale Baume & Mercier Papiere ( Die Garantiekarte",
  "sku": null,
  "code": "HV-408",
  "desc": "Hier präsentieren wir die Baume & Mercier Hampton im Full Set. Die Uhr besteht aus 18-karätigem Weißgold und ist äußerst selten. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p408/0.jpg",
   "assets/products/p408/1.jpg",
   "assets/products/p408/2.jpg",
   "assets/products/p408/3.jpg",
   "assets/products/p408/4.jpg",
   "assets/products/p408/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--baume--mercier-hampton-mv045226-aus-18k-weigold-im-full-set-30e"
 },
 {
  "id": "p406",
  "brand": "Omega",
  "name": "Planet Ocean 39,5 mm",
  "ref": "215.30.40.20.03.001",
  "price": 4450,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2020",
  "size": "39,5 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Omega 8800 Kaliber",
  "sku": null,
  "code": "HV-406",
  "desc": "Hier präsentieren wir die Omega Planet Ocean aus dem Jahr 2020 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p406/0.jpg",
   "assets/products/p406/1.jpg",
   "assets/products/p406/2.jpg",
   "assets/products/p406/3.jpg",
   "assets/products/p406/4.jpg",
   "assets/products/p406/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-395-mm-ref-21530402003001-full-set-2020"
 },
 {
  "id": "p300",
  "brand": "Hublot",
  "name": "Faltschließe aus 18 Karat Rotgold für 20 mm Bandanstoß",
  "ref": null,
  "price": 2290,
  "listPrice": null,
  "status": "available",
  "category": "zubehoer",
  "fullset": null,
  "rating": null,
  "year": null,
  "size": null,
  "material": null,
  "dial": null,
  "strap": null,
  "movement": null,
  "sku": null,
  "code": "HV-300",
  "desc": "Wir bieten hier eine originale Hublot Faltschließe aus 18k Rotgold an. Bandanstoß: 20 mm. Bei weiteren Fragen stehen wir jederzeit zur Verfügung.",
  "images": [
   "assets/products/p300/0.jpg",
   "assets/products/p300/1.jpg",
   "assets/products/p300/2.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--hublot-faltschliee-aus-18-karat-rotgold-fr-20-mm-bandansto-wue5b97l"
 },
 {
  "id": "p292",
  "brand": "IWC",
  "name": "Fliegerchronograph Automatik Zifferblatt Schwarz",
  "ref": "IW377701",
  "price": 3290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Gut",
  "year": "2014",
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-292",
  "desc": "Hier präsentieren wir eine wahre Ikone von IWC Schaffhausen – den IWC Flieger Chronograph. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Gut Glas: Sehr gut Lünette: Gut Armband: Gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p292/0.jpg",
   "assets/products/p292/1.jpg",
   "assets/products/p292/2.jpg",
   "assets/products/p292/3.jpg",
   "assets/products/p292/4.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-fliegerchronograph-iw377701-automatik-zb-schwarz"
 },
 {
  "id": "p334",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean 45 mm",
  "ref": "2200.50.00",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "45 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-334",
  "desc": "Hier präsentieren wir die Omega Planet Ocean mit original Omegabox. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut Gehäuse: Sehr gut Glas: Gut Lünette: Sehr gut Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p334/0.jpg",
   "assets/products/p334/1.jpg",
   "assets/products/p334/2.jpg",
   "assets/products/p334/3.jpg",
   "assets/products/p334/4.jpg",
   "assets/products/p334/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-planet-ocean-45-mm-22005000-uhrenbox"
 },
 {
  "id": "p398",
  "brand": "TAG Heuer",
  "name": "Link Chronograph 150 Stück",
  "ref": null,
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Garantiekarte",
  "rating": "Gut",
  "year": "2013",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik (Calibre 16)",
  "sku": null,
  "code": "HV-398",
  "desc": "Hier präsentieren wir die TAG Heuer Link Chronograph aus 2013 mit Garantiekarte. Diese Uhr ist auf nur 150 Stück limitiert. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p398/0.jpg",
   "assets/products/p398/1.jpg",
   "assets/products/p398/2.jpg",
   "assets/products/p398/3.jpg",
   "assets/products/p398/4.jpg",
   "assets/products/p398/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--tag-heuer-link-chronograph-150-stck-aus-2013-mit-garantiekarte-fog"
 },
 {
  "id": "p298",
  "brand": "TAG Heuer",
  "name": "Carrera Chronograph (2008)",
  "ref": "CV2010",
  "price": 1590,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set",
  "rating": "Gut",
  "year": "2008",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-298",
  "desc": "Hier präsentieren wir die Tag Heuer Carrera Chronograph aus dem Jahr 2008 im Full Set. Alle wichtigen Details auf einen Blick: - Gesamtbewertung: Gut - Gehäuse: Sehr gut - Glas: Vorne (Sehr gut)/ Hinten Kratzer auf den Saphirglasboden - Lünette: Auffällig (siehe Bilder) - Armband: Sehr gut - Schließe: Sehr gut - Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p298/0.jpg",
   "assets/products/p298/1.jpg",
   "assets/products/p298/2.jpg",
   "assets/products/p298/3.jpg",
   "assets/products/p298/4.jpg",
   "assets/products/p298/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-chronograph-refcv2010-aus-2008-im-full-set"
 },
 {
  "id": "p185",
  "brand": "Bvlgari",
  "name": "Octo Finissimo Chronograph GMT",
  "ref": null,
  "price": 11990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut Gehäuse: Sehr gut Glas: Sehr gut Lünette: Sehr gut",
  "year": "2022 Gehäusematerial: Titan Armbandmaterial: Titan Armbandfa",
  "size": "42 mm (Oktogonal) Baujahr: 2022 Gehäusematerial: Titan Armban",
  "material": "Titan Armbandmaterial: Titan Armbandfarbe: Dunkelgrau Ziffer",
  "dial": "Grau Referenznummer: 103068 Uhrwerk: Automatik (Platinrotor)",
  "strap": "Titan Armbandfarbe: Dunkelgrau Zifferblattfarbe: Grau Refere",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-185",
  "desc": "Hier präsentieren wir die Bulgari Octo Finissimo Chronograph GMT aus dem Jahr 2022 im Full Set. Die Octo Finissimo Chronograph GMT bietet die perfekte Mischung aus technischer Raffinesse und ästhetischer Eleganz. Als flachste Automatikuhr der Welt, die mit Chronograph und GMT-Funktion ausgestattet ist.",
  "images": [
   "assets/products/p185/0.jpg",
   "assets/products/p185/1.jpg",
   "assets/products/p185/2.jpg",
   "assets/products/p185/3.jpg",
   "assets/products/p185/4.jpg",
   "assets/products/p185/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/bvlgari-octo-finissimo-chronograph-gmt-jahr-2022-full-set"
 },
 {
  "id": "p366",
  "brand": "TAG Heuer",
  "name": "Link Chronograph Automatik",
  "ref": "CJF2111",
  "price": 1550,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": "nicht bekannt",
  "size": "42 mm",
  "material": "Edelstahl",
  "dial": "Weiß (Außenring leichte Schäden, siehe Bilder)",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-366",
  "desc": "Hier präsentieren wir den TAG Heuer Link Chronograph. Die TAG Heuer hatte im März 2026 einen kompletten Service erhalten und kommt mit 2x Jahren Garantie. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p366/0.jpg",
   "assets/products/p366/1.jpg",
   "assets/products/p366/2.jpg",
   "assets/products/p366/3.jpg",
   "assets/products/p366/4.jpg",
   "assets/products/p366/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-link-chronograph-automatik-cjf2111-service-032026"
 },
 {
  "id": "p399",
  "brand": "Panerai",
  "name": "Luminor Marina Handaufzug",
  "ref": "PAM00632",
  "price": 3990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2016",
  "size": "44 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Leder / Kautschuk",
  "movement": "Handaufzug",
  "sku": null,
  "code": "HV-399",
  "desc": "Hier präsentieren wir die Panerai Luminor Marina PAM00632 im Full Set aus dem Jahr 2016. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p399/0.jpg",
   "assets/products/p399/1.jpg",
   "assets/products/p399/2.jpg",
   "assets/products/p399/3.jpg",
   "assets/products/p399/4.jpg",
   "assets/products/p399/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/panerai-luminor-marina-pam00632-handaufzug-2016-full-set"
 },
 {
  "id": "p263",
  "brand": "TAG Heuer",
  "name": "Carrera GMT big date",
  "ref": "WAR201Z",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": "nicht bekannt",
  "size": "41",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-263",
  "desc": "Hier präsentieren wir den Tag Heuer Carrera GMT Big Date. Diese Tag Heuer hatte im November 2025 eine komplette Revision erhalten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut Gehäuse: Sehr gut Glas: Sehr gut Lünette: Sehr gut Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p263/0.jpg",
   "assets/products/p263/1.jpg",
   "assets/products/p263/2.jpg",
   "assets/products/p263/3.jpg",
   "assets/products/p263/4.jpg",
   "assets/products/p263/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-gmt-big-date-ref-war201z-service-nov-2025"
 },
 {
  "id": "p223",
  "brand": "Omega",
  "name": "Planet Ocean 42 mm",
  "ref": "2201.51.00",
  "price": 3390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2009",
  "size": "42 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-223",
  "desc": "ier präsentieren wir die Omega Planet Ocean 42 mit orange Akzenten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Sehr gut Glas: Gut (Mikrokratzer, siehe Bilder) Lünette: In Ordnung (leichte Kratzer auf der Pos., 3-5 siehe Bilder) Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p223/0.jpg",
   "assets/products/p223/1.jpg",
   "assets/products/p223/2.jpg",
   "assets/products/p223/3.jpg",
   "assets/products/p223/4.jpg",
   "assets/products/p223/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-ref22015100-aus-2009-im-full-set"
 },
 {
  "id": "p246",
  "brand": "TAG Heuer",
  "name": "Carrera Chronograph (2007)",
  "ref": "CV2010",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut / gut",
  "year": "2007",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-246",
  "desc": "Hier präsentieren wir die Tag Heuer Carrera. Diese Tag Heuer hatte im November 2025 eine komplette Revision erhalten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut / gut Gehäuse: Sehr gut Glas: Sehr gut Lünette: Sehr gut (Lünette Pos. 3-4 Schlag) Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p246/0.jpg",
   "assets/products/p246/1.jpg",
   "assets/products/p246/2.jpg",
   "assets/products/p246/3.jpg",
   "assets/products/p246/4.jpg",
   "assets/products/p246/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-chronograph-ref-cv2010-service-2025-full-set"
 },
 {
  "id": "p393",
  "brand": "Rolex",
  "name": "Datejust 41 Zifferblatt Black Neu",
  "ref": "126300",
  "price": 9900,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Neu",
  "year": "2026",
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-393",
  "desc": "Hier präsentieren wir die Rolex Datejust 41 aus dem Jahr 2026 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p393/0.jpg",
   "assets/products/p393/1.jpg",
   "assets/products/p393/2.jpg",
   "assets/products/p393/3.jpg",
   "assets/products/p393/4.jpg",
   "assets/products/p393/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-41-zb-black-126300-neu-aus-2026-im-full-set"
 },
 {
  "id": "p335",
  "brand": "Breitling",
  "name": "Chronomat Burgundy Dial",
  "ref": "B13047",
  "price": 2190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": "Gut",
  "year": null,
  "size": "39 mm",
  "material": "Edelstahl",
  "dial": "Burgundy Dial",
  "strap": "Leder",
  "movement": "Geprüft auf einwandfreies Laufverhalten, kein anstehender Se",
  "sku": null,
  "code": "HV-335",
  "desc": "Hier präsentieren wir die Breitling Chronomat in Stahl/Gold mit Echtheitszertifikat. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Gut erkennbar Glas: Sehr gut Lünette: Gut erkennbar Armband: Sehr gut Schließe: Sehr gut (After market, siehe Bilder) Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p335/0.jpg",
   "assets/products/p335/1.jpg",
   "assets/products/p335/2.jpg",
   "assets/products/p335/3.jpg",
   "assets/products/p335/4.jpg",
   "assets/products/p335/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-chronomat-b13047-burgundy-dial-mit-echtheitszertifikat"
 },
 {
  "id": "p384",
  "brand": "Omega",
  "name": "Planet Ocean 45,5 mm",
  "ref": "232.90.46.51.03.001",
  "price": 4890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2014",
  "size": "45,5 mm",
  "material": "Titan",
  "dial": "Blau",
  "strap": "Titan",
  "movement": "Automatik 9300 Kaliber",
  "sku": null,
  "code": "HV-384",
  "desc": "Hier präsentieren wir die Omega Planet Ocean Chronograph aus dem Jahr 2014 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p384/0.jpg",
   "assets/products/p384/1.jpg",
   "assets/products/p384/2.jpg",
   "assets/products/p384/3.jpg",
   "assets/products/p384/4.jpg",
   "assets/products/p384/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-23290465103001-aus-2014-im-full-set"
 },
 {
  "id": "p283",
  "brand": "Omega",
  "name": "Planet Ocean 43,5 mm",
  "ref": "215.30.44.21.03.001",
  "price": 4190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2018",
  "size": "43,5 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Omega Co-Axial",
  "sku": null,
  "code": "HV-283",
  "desc": "Hier präsentieren wir die Omega Planet Ocean aus dem Jahr 2018 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p283/0.jpg",
   "assets/products/p283/1.jpg",
   "assets/products/p283/2.jpg",
   "assets/products/p283/3.jpg",
   "assets/products/p283/4.jpg",
   "assets/products/p283/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-435-mm-ref-21530442103001-full-set-2018"
 },
 {
  "id": "p395",
  "brand": "Omega",
  "name": "Seamaster Aqua Terra GMT",
  "ref": "231.10.43.22.03.001",
  "price": 3950,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": "nicht bekannt",
  "size": "43 mm",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Leder (guter Zustand)",
  "movement": "Automatik (Manufakturkaliber)",
  "sku": null,
  "code": "HV-395",
  "desc": "Hier präsentieren wir die Omega Seamaster Aqua Terra. Für alle, die nicht nur die Zeit im Blick haben, sondern gleich mehrere. Die Omega Aqua Terra hatte im Frühjahr 2025 eine komplette Revision bei einem Uhrmacher erhalten. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p395/0.jpg",
   "assets/products/p395/1.jpg",
   "assets/products/p395/2.jpg",
   "assets/products/p395/3.jpg",
   "assets/products/p395/4.jpg",
   "assets/products/p395/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-aqua-terra-gmt-23110432203001-service-2025"
 },
 {
  "id": "p350",
  "brand": "TAG Heuer",
  "name": "Carrera Calibre 16 Chronograph",
  "ref": "CBM2110.BA065",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "41 mm",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-350",
  "desc": "Hier präsentieren wir die TAG Heuer Carrera Calibre 16. Der Listenpreis der Tag Heuer liegt bei 5.800 Euro in Deutschland. Unsere Bilder sind unbearbeitet und zeigen jedes Detail – mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p350/0.jpg",
   "assets/products/p350/1.jpg",
   "assets/products/p350/2.jpg",
   "assets/products/p350/3.jpg",
   "assets/products/p350/4.jpg",
   "assets/products/p350/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-calibre-16-cbm2110ba065-chronograph"
 },
 {
  "id": "p357",
  "brand": "IWC",
  "name": "Portofino 37 Automatic Silber Dia dial",
  "ref": "IW458101",
  "price": 3190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Garantiekarte",
  "rating": "Sehr gut",
  "year": "2021",
  "size": "37 mm",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Automatik",
  "sku": null,
  "code": "HV-357",
  "desc": "Hier präsentieren wir die IWC Portofino 37 aus dem Jahr 2021 im Full Set mit einer Restgarantie bei IWC bis 2029. Unsere Bilder sind unbearbeitet und zeigen jedes Detail, mehr als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p357/0.jpg",
   "assets/products/p357/1.jpg",
   "assets/products/p357/2.jpg",
   "assets/products/p357/3.jpg",
   "assets/products/p357/4.jpg",
   "assets/products/p357/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portofino-37-automatic-iw458101-silber-dia-dial-2021-full-set"
 }
];

window.FLAGSHIP_ID = "p462";
window.NEW_IN = ["p2162", "p5069", "p4846", "p4808", "p3771", "p2446"];

window.TESTIMONIALS = [
 {
  "name": "Andrea M.",
  "img": "assets/img/reviews/andrea-m.jpg",
  "text": "Communication with seller has been easy, and the watch matched the offer perfectly. Hannes is a very nice person to exchange messages with, adding a personal touch to the interaction. thank you!"
 },
 {
  "name": "Marcel N.",
  "img": "assets/img/reviews/marcel-n.jpg",
  "text": "Hallo Hannes & Minh, ich bin super happy mit der Uhr, sie ist in einem Top-Zustand! Danke für den tollen Service und dass ihr mein Wunschmodell so schnell besorgen konntet 👌🏽"
 },
 {
  "name": "Stephan L.",
  "img": "assets/img/reviews/stephan-l.jpg",
  "text": "Watch looks very good. I am very happy! Thx for all. I hope to meet you someday for something else"
 },
 {
  "name": "Giuseppe F.",
  "img": "assets/img/reviews/giuseppe-f.jpg",
  "text": "Hey guys. Everything ok, package arrived, watch perfect. Thank you very much for everything."
 },
 {
  "name": "Christian H.",
  "img": "assets/img/reviews/christian-h.jpg",
  "text": "Servus Hannes, Uhr ist da, bin mega zufrieden, danke fürs organisieren, gerne wieder."
 },
 {
  "name": "Damian M.",
  "img": "assets/img/reviews/damian-m.jpg",
  "text": "Ist angekommen. Danke auch für den netten Kontakt und den schnellen Versand und bis zum nächsten Mal. 😁"
 },
 {
  "name": "Mikel U.",
  "img": "assets/img/reviews/mikel-u.jpg",
  "text": "Thank you so much. It was a very smooth communication. Looking forward for the next watch and enjoy wearing this IWC!"
 },
 {
  "name": "Günther H.",
  "img": "assets/img/reviews/guenther-h.jpg",
  "text": "Ihr habt es geschafft (wie euch das gelungen ist kann ich echt nicht sagen) mir 2 megageile Uhren um 12k anzudrehen 😂 unglaulich."
 }
];

window.FAQ = [
 {
  "q": "Sind alle Uhren auf Echtheit geprüft?",
  "a": "Ja. Jede Uhr wird vor dem Verkauf sorgfältig geprüft. Dabei arbeiten wir sowohl in Deutschland als auch in Korea mit erfahrenen Uhrmachern zusammen. Zusätzlich erhält jede Uhr von uns ein Echtheitszertifikat."
 },
 {
  "q": "Welche Garantie erhalte ich?",
  "a": "Auf jede Uhr geben wir 12 Monate Garantie auf das Werk — zusätzlich zu einer eventuell noch laufenden Herstellergarantie. Viele unserer Uhren kommen zudem mit frischem Servicenachweis."
 },
 {
  "q": "Kann ich eine Uhr zurückgeben?",
  "a": "Ja, Sie haben 14 Tage Rückgaberecht. Die Uhr muss sich im gelieferten Zustand befinden, inklusive Uhrenbox, Papiere und Zubehörteile."
 },
 {
  "q": "Wie läuft die Übergabe ab?",
  "a": "Wahlweise per weltweit versichertem Wertversand oder unsere Empfehlung: persönlich in unserem Showroom im Garden Tower in der 7. Etage im Frankfurter Bankenviertel. Termine vereinbaren Sie unkompliziert per WhatsApp, E-Mail oder telefonisch."
 },
 {
  "q": "Nehmen Sie meine Uhr in Zahlung?",
  "a": "Sehr gerne. Senden Sie uns über die Ankauf-Seite Fotos und Eckdaten Ihrer Uhr. Sie erhalten innerhalb von 12 Stunden ein konkretes Angebot, das Sie direkt mit einem Kauf verrechnen können."
 },
 {
  "q": "Ich suche eine bestimmte Uhr. Können Sie sie beschaffen?",
  "a": "Das ist eine unserer Stärken. Über unser Netzwerk in Südkorea und Europa finden wir Referenzen, die auf dem Markt kaum zu bekommen sind. Stellen Sie einfach einen Suchauftrag."
 }
];

/* Shopify: Storefront-Zugang und feste Produktzuordnung. */
window.SHOPIFY = {
 "domain": "tami1g-0j.myshopify.com",
 "storefrontAccessToken": "89c87251e5d1f73c1302b1674ba75b69",
 "products": {
   "p2162": "10219856462152",
   "p5069": "10219856560456",
   "p4846": "10219856625992",
   "p4808": "10219856724296",
   "p3771": "10219856789832",
   "p2446": "10219856888136",
   "p1226": "10219856986440",
   "p9311": "10219857150280",
   "p9290": "10219857248584",
   "p7474": "10219857314120",
   "p1799": "10219857412424",
   "p9177": "10219857510728",
   "p6059": "10219857576264",
   "p5825": "10219857674568",
   "p5085": "10219857740104",
   "p5044": "10219857871176",
   "p5038": "10219857969480",
   "p3766": "10219858035016",
   "p3762": "10219858166088",
   "p4284": "10219858231624",
   "p4267": "10219858297160",
   "p7015": "10219858362696",
   "p3734": "10219858428232",
   "p5556": "10219858493768",
   "p5555": "10219858559304",
   "p1237": "10219858657608",
   "p1218": "10219858723144",
   "p1157": "10219858821448",
   "p1154": "10219858886984",
   "p9012": "10219858985288",
   "p454": "10219712250184",
   "p450": "10219712381256",
   "p441": "10219712643400",
   "p440": "10219859083592",
   "p427": "10219712774472",
   "p420": "10219712905544",
   "p415": "10219712971080",
   "p334": "10219713724744",
   "p185": "10219714085192",
   "p366": "10219713495368",
   "p263": "10219714019656",
   "p223": "10219901256008",
   "p335": "10219713691976",
   "p395": "10219713298760",
   "p350": "10219713659208",
   "p9320": "10219857051976",
   "p462": "10219711955272",
   "p458": "10219712151880",
   "p446": "10219712479560",
   "p435": "10219712741704",
   "p434": "10219712545096",
   "p426": "10219651006792",
   "p413": "10219713036616",
   "p412": "10219713069384",
   "p408": "10219713102152",
   "p406": "10219713167688",
   "p300": "10219713921352",
   "p292": "10219713954120",
   "p398": "10219713134920",
   "p298": "10219713888584",
   "p399": "10219713200456",
   "p246": "10219713823048",
   "p393": "10219713331528",
   "p384": "10219712872776",
   "p283": "10219713986888",
   "p357": "10219713626440"
 }
};
