/* HAHN & VO — data layer (single source of truth).
   Generated from live hahn-vo.de inventory, 2026-08-10. */
window.SITE = {
 "company": "Hahn & Vo OHG",
 "owners": "Hannes Hahn & Minh Vo",
 "email": "info@hahntime.com",
 "phone": "+49 176 8421 1760",
 "whatsapp": "https://wa.me/4917684211760",
 "instagram": "https://www.instagram.com/hahn.vo/",
 "instagramHandle": "@hahn.vo",
 "tiktok": "https://www.tiktok.com/@hahn.vo",
 "showroom": "Garden Tower · 7. Etage, Neue Mainzer Straße 46–50, 60311 Frankfurt am Main",
 "legalAddress": "Luisenstraße 81, 63067 Offenbach am Main",
 "vatId": "DE453178178",
 "register": "HRA 43504",
 "whatsappChannel": "https://whatsapp.com/channel/0029VbAuiZnEawdspdIfjW1i",
 "youtube": ""
};

window.PRODUCTS = [
 {
  "id": "p462",
  "brand": "MB&F",
  "name": "Legacy Machine Split Escapement EVO Titan",
  "ref": "04.TR.LB",
  "price": 109900,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut (wie neu)",
  "year": "2024",
  "size": "44 mm",
  "sku": "MB-F-LGC-MCH",
  "material": "Titan",
  "dial": "Blau",
  "strap": "Kautschukband",
  "movement": "Handaufzug",
  "desc": "Hier präsentieren wir die MB&F Legacy Machine Split Escapement aus dem Jahr 2024 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p462/0.jpg",
   "assets/products/p462/1.jpg",
   "assets/products/p462/2.jpg",
   "assets/products/p462/3.jpg",
   "assets/products/p462/4.jpg",
   "assets/products/p462/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/mbf-legacy-machine-split-escapement-titan-04trlb-full-set-2024"
 },
 {
  "id": "p461",
  "brand": "Cartier",
  "name": "Tank Solo Quarz, römisches Zifferblatt",
  "ref": "2716",
  "price": 2790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": null,
  "year": null,
  "size": null,
  "sku": "CRT-TNK-SL-271",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder",
  "movement": "Quarz 12",
  "desc": "Hier präsentieren wir die Cartier Tank Solo. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p461/0.jpg",
   "assets/products/p461/1.jpg",
   "assets/products/p461/2.jpg",
   "assets/products/p461/3.jpg",
   "assets/products/p461/4.jpg",
   "assets/products/p461/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/cartier-tank-solo-2716-quarz-24-x-31"
 },
 {
  "id": "p460",
  "brand": "Cartier",
  "name": "Tank Solo Piano Dial 24 × 31 mm",
  "ref": null,
  "price": 6700,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Echtheitszertifikat, Box",
  "rating": null,
  "year": "2010",
  "size": null,
  "sku": "CRT-TNK-SL-PN",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die Cartier Tank Solo aus dem Jahr 2010 im Full Set. Die Cartier mit seltenem Piano Dial ist unter Sammlern äußerst begehrt und gilt als gesuchtes Sammlerstück. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p460/0.jpg",
   "assets/products/p460/1.jpg",
   "assets/products/p460/2.jpg",
   "assets/products/p460/3.jpg",
   "assets/products/p460/4.jpg",
   "assets/products/p460/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/cartier-tank-solo-piano-dial-24-x-31-full-set-2010"
 },
 {
  "id": "p459",
  "brand": "Rolex",
  "name": "Datejust 36, blaues Zifferblatt, Oysterband",
  "ref": "116200",
  "price": 6350,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2009",
  "size": "36 mm",
  "sku": "RLX-DTJ-36-ZB2",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 im Full Set aus dem Jahr 2009. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p459/2.jpg",
   "assets/products/p459/0.jpg",
   "assets/products/p459/1.jpg",
   "assets/products/p459/3.jpg",
   "assets/products/p459/4.jpg",
   "assets/products/p459/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-zb-blau-116200-oysterband-full-set-jahr-2009"
 },
 {
  "id": "p458",
  "brand": "Rolex",
  "name": "Datejust 36, blaues Zifferblatt, Jubilee",
  "ref": "126200",
  "price": 9490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2022",
  "size": "36 mm",
  "sku": "RLX-DTJ-36-ZB1",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 neuwertig & ungetragen aus dem Jahr 2022 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p458/0.jpg",
   "assets/products/p458/1.jpg",
   "assets/products/p458/2.jpg",
   "assets/products/p458/3.jpg",
   "assets/products/p458/4.jpg",
   "assets/products/p458/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-zb-blau-126200-jubilee-automatik-neu-jahr-2022"
 },
 {
  "id": "p457",
  "brand": "Omega",
  "name": "Speedmaster 38 mm",
  "ref": "324.30.38.50.06.001",
  "price": 3790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2018",
  "size": "38 mm",
  "sku": "MG-SPD-38M-324",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Speedmaster aus dem Jahr 2018 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p457/0.jpg",
   "assets/products/p457/1.jpg",
   "assets/products/p457/2.jpg",
   "assets/products/p457/3.jpg",
   "assets/products/p457/4.jpg",
   "assets/products/p457/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-speedmaster-38mm-32430385006001-full-set-2018"
 },
 {
  "id": "p456",
  "brand": "Glashütte Original",
  "name": "Panomatic Lunar",
  "ref": "1-90-02-42-32-05",
  "price": 8290,
  "listPrice": null,
  "status": "reserved",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2022",
  "size": "40 mm",
  "sku": "XN-GLS-RGN-PNM",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die Glashütte Original Panomatic Lunar aus dem Jahr 2022 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p456/0.jpg",
   "assets/products/p456/1.jpg",
   "assets/products/p456/2.jpg",
   "assets/products/p456/3.jpg",
   "assets/products/p456/4.jpg",
   "assets/products/p456/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--glashtte-original-panomatic-lunar-1-90-02-42-32-05-full-set-2022-pug"
 },
 {
  "id": "p454",
  "brand": "IWC",
  "name": "Big Pilot Top Gun Keramik 46 mm",
  "ref": "IW502001",
  "price": 7790,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2017",
  "size": "46 mm",
  "sku": "IWC-BIG-PLT-TOP",
  "material": "Keramik",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die IWC Big Pilot Top Gun aus dem Jahr 2017 im Full Set.",
  "images": [
   "assets/products/p454/0.jpg",
   "assets/products/p454/1.jpg",
   "assets/products/p454/2.jpg",
   "assets/products/p454/3.jpg",
   "assets/products/p454/4.jpg",
   "assets/products/p454/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-big-pilot-top-gun-keramik-46mm-iw502001-full-set-2017"
 },
 {
  "id": "p452",
  "brand": "Rolex",
  "name": "Submariner Date",
  "ref": "126610LN",
  "price": 11950,
  "listPrice": null,
  "status": "reserved",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2022",
  "size": "41 mm",
  "sku": "RLX-SBM-DT-126",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Rolex Submariner Date aus dem Jahr 2022 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p452/0.jpg",
   "assets/products/p452/1.jpg",
   "assets/products/p452/2.jpg",
   "assets/products/p452/3.jpg",
   "assets/products/p452/4.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-submariner-date-126610ln-full-set-automatik-jahr-2022"
 },
 {
  "id": "p451",
  "brand": "Sinn",
  "name": "103 St Chronograph Automatik",
  "ref": "103",
  "price": 2190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2015",
  "size": "41 mm",
  "sku": "SNN-103-CHR-TMT",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Sinn 103 Chronograph aus dem Jahr 2015 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p451/0.jpg",
   "assets/products/p451/1.jpg",
   "assets/products/p451/2.jpg",
   "assets/products/p451/3.jpg",
   "assets/products/p451/4.jpg",
   "assets/products/p451/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/sinn-103-chronograph-automatik-41mm-2015-full-set"
 },
 {
  "id": "p450",
  "brand": "IWC",
  "name": "Portugieser Handaufzug",
  "ref": "IW545405",
  "price": 4190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Garantiekarte, Box",
  "rating": null,
  "year": null,
  "size": "44 mm",
  "sku": "IWC-PRT-HND-W54",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die IWC Portugieser Handaufzug mit Box und Service-Garantiekarte. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p450/0.jpg",
   "assets/products/p450/1.jpg",
   "assets/products/p450/2.jpg",
   "assets/products/p450/3.jpg",
   "assets/products/p450/4.jpg",
   "assets/products/p450/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portugieser-handaufzug-iw545405-box-service-garantiekarte"
 },
 {
  "id": "p387",
  "brand": "Omega",
  "name": "Globemaster Constellation Stahl / Gold",
  "ref": "130.23.39.21.03.001",
  "price": 5650,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Papiere, Garantiekarte, Box",
  "rating": null,
  "year": "2018",
  "size": "39 mm",
  "sku": "MG-GLB-CNS-130",
  "material": "Stahl / Gold",
  "dial": "Blau",
  "strap": "Leder",
  "movement": "Automatik (Omega Manufakturkaliber)",
  "desc": "Hier präsentieren wir die Omega Globemaster Constellation 39 mm in Stahl / Gold. Diese Globemaster hatte im Sommer 2024 einen Service bei Omega gehabt. Der Vorbesitzer hat leider die Garantiekarte & Servicepapiere verloren, jedoch haben wir davon jeweils die Fotos. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p387/0.jpg",
   "assets/products/p387/1.jpg",
   "assets/products/p387/2.jpg",
   "assets/products/p387/3.jpg",
   "assets/products/p387/4.jpg",
   "assets/products/p387/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-globemaster-constellation-13023392103001-stahl--gold"
 },
 {
  "id": "p446",
  "brand": "Jaeger-LeCoultre",
  "name": "Reverso Classic Handaufzug",
  "ref": null,
  "price": 6290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2019",
  "size": "40.1 mm",
  "sku": "JGR-LE-CLT-RVR",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die Jaeger Le Coultre Reverso aus dem Jahr 2019 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p446/0.jpg",
   "assets/products/p446/1.jpg",
   "assets/products/p446/2.jpg",
   "assets/products/p446/3.jpg",
   "assets/products/p446/4.jpg",
   "assets/products/p446/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/jaeger-le-coultre-reverso-handaufzug-401mm-2019-full-set"
 },
 {
  "id": "p449",
  "brand": "Rolex",
  "name": "Datejust 36 Perlmutt-Diamant-Zifferblatt",
  "ref": "16014",
  "price": 5490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": null,
  "year": "1983",
  "size": "36 mm",
  "sku": "RLX-DTJ-36-MOP",
  "material": "Edelstahl",
  "dial": "MOP Diamond Dial (aftermarket)",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Rolex Datejust 36 aus dem Jahr 1983 mit Originalbox. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p449/0.jpg",
   "assets/products/p449/1.jpg",
   "assets/products/p449/2.jpg",
   "assets/products/p449/3.jpg",
   "assets/products/p449/4.jpg",
   "assets/products/p449/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-mop-diamond-dial-16014-original-rolex-box-1983"
 },
 {
  "id": "p434",
  "brand": "Nomos",
  "name": "Ludwig Handaufzug 34 mm",
  "ref": "205",
  "price": 1190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2011",
  "size": "34 mm",
  "sku": "NMS-LDW-34M-205",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Leder (stark gebraucht)",
  "movement": null,
  "desc": "Hier präsentieren wir die Nomos Luwdwig aus dem Jahr 2011 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p434/0.jpg",
   "assets/products/p434/1.jpg",
   "assets/products/p434/2.jpg",
   "assets/products/p434/3.jpg",
   "assets/products/p434/4.jpg",
   "assets/products/p434/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/nomos-ludwig-34mm-205-handaufzug-aus-2011-im-full-set"
 },
 {
  "id": "p444",
  "brand": "Rolex",
  "name": "Datejust 41 Weißgold-Lünette Jubilee",
  "ref": "126334",
  "price": 13990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2026",
  "size": "41 mm",
  "sku": "XN-RLX-DTJ-41",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Rolex Datejust 41 aus dem Jahr 2026 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p444/0.jpg",
   "assets/products/p444/1.jpg",
   "assets/products/p444/2.jpg",
   "assets/products/p444/3.jpg",
   "assets/products/p444/4.jpg",
   "assets/products/p444/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--rolex-datejust-41-weigold-126334-jubilee-neu-052026-full-set-52e"
 },
 {
  "id": "p443",
  "brand": "Omega",
  "name": "Seamaster Vintage 36 mm, blau",
  "ref": "2501.81",
  "price": 1590,
  "listPrice": null,
  "status": "sold",
  "category": "uhren",
  "fullset": null,
  "rating": null,
  "year": null,
  "size": "36 mm",
  "sku": "MG-SMS-VNT-BL",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik 12",
  "desc": "Hier präsentieren wir die Omega Seamaster Vintage. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p443/0.jpg",
   "assets/products/p443/1.jpg",
   "assets/products/p443/2.jpg",
   "assets/products/p443/3.jpg",
   "assets/products/p443/4.jpg",
   "assets/products/p443/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-vintage-blau-36mm-ref-250181"
 },
 {
  "id": "p441",
  "brand": "Longines",
  "name": "Saint-Imier Chronograph 41 mm",
  "ref": "L2.752.4.72.6",
  "price": 1850,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": null,
  "year": null,
  "size": "41 mm",
  "sku": "LNG-SNT-MR-CHR",
  "material": "Edelstahl",
  "dial": "Weiß",
  "strap": "Edelstahl",
  "movement": "Automatik 12",
  "desc": "Hier präsentieren wir die Rolex Longines Saint-Imier Chronograph. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p441/0.jpg",
   "assets/products/p441/1.jpg",
   "assets/products/p441/2.jpg",
   "assets/products/p441/3.jpg",
   "assets/products/p441/4.jpg",
   "assets/products/p441/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/longines-saint-imier-chronograph-41mm-l27524726"
 },
 {
  "id": "p439",
  "brand": "Cartier",
  "name": "Clé de Cartier",
  "ref": "WSCL0006",
  "price": 3850,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2017",
  "size": "35 mm",
  "sku": "CRT-CLE-DE-CRT",
  "material": "Edelstahl",
  "dial": "Weiß römisch",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Cartier Cle de Cartier aus dem Jahr 2017 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p439/0.jpg",
   "assets/products/p439/1.jpg",
   "assets/products/p439/2.jpg",
   "assets/products/p439/3.jpg",
   "assets/products/p439/4.jpg",
   "assets/products/p439/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/cartier-cle-de-cartier-wscl0006-aus-2017-im-full-set"
 },
 {
  "id": "p438",
  "brand": "Breitling",
  "name": "Superocean Héritage",
  "ref": "A1732024/B868",
  "price": 3190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2016",
  "size": "46 mm",
  "sku": "BRT-SPR-HRT-173",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Breitling Superocean Heritage aus dem Jahr 2016 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p438/0.jpg",
   "assets/products/p438/1.jpg",
   "assets/products/p438/2.jpg",
   "assets/products/p438/3.jpg",
   "assets/products/p438/4.jpg",
   "assets/products/p438/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-superocean-heritage-a1732024b868-aus-2016-im-full-set"
 },
 {
  "id": "p435",
  "brand": "Rolex",
  "name": "Oyster Perpetual 34 „Med Blue“",
  "ref": "124200",
  "price": 7490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2026",
  "size": "34 mm",
  "sku": "RLX-YST-PRP-34",
  "material": "Edelstahl 904L",
  "dial": "Med Blue",
  "strap": "Edelstahl 904L",
  "movement": null,
  "desc": "Hier präsentieren wir die Rolex Oyster Perpetual 34 aus dem Jahr 2026 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p435/0.jpg",
   "assets/products/p435/1.jpg",
   "assets/products/p435/2.jpg",
   "assets/products/p435/3.jpg",
   "assets/products/p435/4.jpg",
   "assets/products/p435/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-oyster-perpetual-34-mm-124200-med-blue-2026-im-full-set"
 },
 {
  "id": "p427",
  "brand": "Tudor",
  "name": "Royal 34 mm",
  "ref": "28400",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2021",
  "size": "34 mm",
  "sku": "TDR-RYL-34-MM",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Tudor Royal 34 aus dem Jahr 2021 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p427/0.jpg",
   "assets/products/p427/1.jpg",
   "assets/products/p427/2.jpg",
   "assets/products/p427/3.jpg",
   "assets/products/p427/4.jpg",
   "assets/products/p427/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-royal-34-mm-ref-28400-aus-2021-im-full-set"
 },
 {
  "id": "p426",
  "brand": "Tudor",
  "name": "Black Bay 36 Stahl/Gelbgold",
  "ref": "79503",
  "price": 3390,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2022",
  "size": "36 mm",
  "sku": "TDR-BLC-BAY-36",
  "material": "Edelstahl/Gelbgold",
  "dial": "Schwarz",
  "strap": "Edelstahl/Gelbgold",
  "movement": null,
  "desc": "Hier präsentieren wir die Tudor Black Bay Stahl/Gold aus dem Jahr 2022 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p426/0.jpg",
   "assets/products/p426/1.jpg",
   "assets/products/p426/2.jpg",
   "assets/products/p426/3.jpg",
   "assets/products/p426/4.jpg",
   "assets/products/p426/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tudor-black-bay-36-stgg-79503-aus-2022-im-full-set"
 },
 {
  "id": "p407",
  "brand": "Omega",
  "name": "Aqua Terra",
  "ref": "231.10.42.21.01.003",
  "price": 3890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2015",
  "size": "41,5 mm",
  "sku": "MG-Q-TRR-231",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Aqua Terra aus dem Jahr 2015 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p407/0.jpg",
   "assets/products/p407/1.jpg",
   "assets/products/p407/2.jpg",
   "assets/products/p407/3.jpg",
   "assets/products/p407/4.jpg",
   "assets/products/p407/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-aqua-terra-23110422101003-aus-2015-im-full-set"
 },
 {
  "id": "p424",
  "brand": "IWC",
  "name": "Pilot’s Watch Spitfire Chronograph",
  "ref": "IW377719",
  "price": 4250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Papiere, Garantiekarte, Box",
  "rating": null,
  "year": "2018",
  "size": "43 mm",
  "sku": "IWC-SCH-FLG-SPT",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die IWC Fliegeruhr Spitfire aus 2018 mit Garantiekarte, Booklets und IWC Travelbox. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p424/0.jpg",
   "assets/products/p424/1.jpg",
   "assets/products/p424/2.jpg",
   "assets/products/p424/3.jpg",
   "assets/products/p424/4.jpg",
   "assets/products/p424/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-schaffhausen-fliegeruhr-spitfire-chronograph-iw377719-zb-grau"
 },
 {
  "id": "p384",
  "brand": "Omega",
  "name": "Planet Ocean",
  "ref": "232.90.46.51.03.001",
  "price": 4890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2014",
  "size": "45,5 mm",
  "sku": "MG-PLN-CN-232",
  "material": "Titan",
  "dial": "Blau",
  "strap": "Titan",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Planet Ocean Chronograph aus dem Jahr 2014 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p384/0.jpg",
   "assets/products/p384/1.jpg",
   "assets/products/p384/2.jpg",
   "assets/products/p384/3.jpg",
   "assets/products/p384/4.jpg",
   "assets/products/p384/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-23290465103001-aus-2014-im-full-set"
 },
 {
  "id": "p420",
  "brand": "IWC",
  "name": "Portofino 8 days Blau",
  "ref": "IW510106",
  "price": 5190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2015",
  "size": "45 mm",
  "sku": "IWC-PRT-8-DYS",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die IWC Portofino 8 Days aus dem Jahr 2015 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p420/0.jpg",
   "assets/products/p420/1.jpg",
   "assets/products/p420/2.jpg",
   "assets/products/p420/3.jpg",
   "assets/products/p420/4.jpg",
   "assets/products/p420/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portofino-8-days-blau-iw510106-aus-2015-im-full-set"
 },
 {
  "id": "p351",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean 42 mm",
  "ref": "2201.51.00",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Papiere",
  "rating": "Gut",
  "year": "2012",
  "size": "42 mm",
  "sku": "MG-PLN-CN-42",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik Originale Omega Papiere 12",
  "desc": "Hier präsentieren wir die Omega Planet Ocean 42 mit orangefarbenen Akzenten. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p351/0.jpg",
   "assets/products/p351/1.jpg",
   "assets/products/p351/2.jpg",
   "assets/products/p351/3.jpg",
   "assets/products/p351/4.jpg",
   "assets/products/p351/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-42-automatik-22015100-jahr-2011"
 },
 {
  "id": "p415",
  "brand": "Breitling",
  "name": "Navitimer B01 Chronograph",
  "ref": "AB0121211C1A1",
  "price": 5550,
  "listPrice": 9350,
  "status": "reserved",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2018",
  "size": "43 mm",
  "sku": "BRT-NVT-B01-CHR",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Breitling Navitimer B01 Chronograph im Full Set mit frischer Garantie (April 2026). Der aktuelle Breitling-Listenpreis liegt bei 9.350 Euro. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p415/0.jpg",
   "assets/products/p415/1.jpg",
   "assets/products/p415/2.jpg",
   "assets/products/p415/3.jpg",
   "assets/products/p415/4.jpg",
   "assets/products/p415/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-navitimer-b01-chronograph-ab0121211c1a1-full-set-service-april-2026"
 },
 {
  "id": "p413",
  "brand": "Tudor",
  "name": "Black Bay Heritage 41, rote Lünette",
  "ref": "79230R-0003",
  "price": 2550,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "41 mm",
  "sku": "XN-TDR-BLC-BAY",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Tudor Black Bay Heritage 41. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p413/0.jpg",
   "assets/products/p413/1.jpg",
   "assets/products/p413/2.jpg",
   "assets/products/p413/3.jpg",
   "assets/products/p413/4.jpg",
   "assets/products/p413/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--tudor-black-bay-heritage-41-lnette-rot-79230r-0003-tudor-box-7gg"
 },
 {
  "id": "p412",
  "brand": "Breitling",
  "name": "Avenger II GMT",
  "ref": "A32390",
  "price": 2250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "43 mm",
  "sku": "BRT-VNG-II-GMT",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Leder",
  "movement": "Automatik",
  "desc": "Hier kommt die Breitling Avenger II GMT. Für alle, die nicht nur eine, sondern gleich zwei Zeitzonen im Griff haben wollen. Natürlich inklusive originaler Box, damit sie sich auch nach dem Flug stilvoll ausruhen kann. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p412/0.jpg",
   "assets/products/p412/1.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-ii-gmt-automatik-a32390-lederband-breitling-box"
 },
 {
  "id": "p408",
  "brand": "Baume & Mercier",
  "name": "Hampton 18 K Weißgold",
  "ref": "MV045226",
  "price": 3490,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Garantiekarte, Box",
  "rating": null,
  "year": null,
  "size": "26 x 40 mm",
  "sku": "XN-BM-MRC-HMP",
  "material": "Weißgold",
  "dial": "Weiß",
  "strap": "Leder",
  "movement": "Quarz Originale Baume & Mercier Papiere",
  "desc": "Hier präsentieren wir die Baume & Mercier Hampton im Full Set. Die Uhr besteht aus 18-karätigem Weißgold und ist äußerst selten. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p408/0.jpg",
   "assets/products/p408/1.jpg",
   "assets/products/p408/2.jpg",
   "assets/products/p408/3.jpg",
   "assets/products/p408/4.jpg",
   "assets/products/p408/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--baume--mercier-hampton-mv045226-aus-18k-weigold-im-full-set-30e"
 },
 {
  "id": "p398",
  "brand": "Tag Heuer",
  "name": "Link Chronograph — limitiert auf 150 Stück",
  "ref": null,
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Papiere, Garantiekarte",
  "rating": null,
  "year": "2013",
  "size": "41 mm",
  "sku": "XN-TAG-HR-LNK",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die TAG Heuer Link Chronograph aus 2013 mit Garantiekarte. Diese Uhr ist auf nur 150 Stück limitiert. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p398/0.jpg",
   "assets/products/p398/1.jpg",
   "assets/products/p398/2.jpg",
   "assets/products/p398/3.jpg",
   "assets/products/p398/4.jpg",
   "assets/products/p398/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--tag-heuer-link-chronograph-150-stck-aus-2013-mit-garantiekarte-fog"
 },
 {
  "id": "p406",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean 39,5 mm",
  "ref": "215.30.40.20.03.001",
  "price": 4450,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2020",
  "size": "39,5 mm",
  "sku": "MG-PLN-CN-39",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Planet Ocean aus dem Jahr 2020 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p406/0.jpg",
   "assets/products/p406/1.jpg",
   "assets/products/p406/2.jpg",
   "assets/products/p406/3.jpg",
   "assets/products/p406/4.jpg",
   "assets/products/p406/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-395-mm-ref-21530402003001-full-set-2020"
 },
 {
  "id": "p399",
  "brand": "Panerai",
  "name": "Luminor Marina Handaufzug 2016",
  "ref": "PAM00632",
  "price": 3990,
  "listPrice": null,
  "status": "reserved",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2016",
  "size": "44 mm",
  "sku": "PNR-LMN-MRN-PM0",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Leder / Kautschuk",
  "movement": "Handaufzug",
  "desc": "Hier präsentieren wir die Panerai Luminor Marina PAM00632 im Full Set aus dem Jahr 2016. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p399/0.jpg",
   "assets/products/p399/1.jpg",
   "assets/products/p399/2.jpg",
   "assets/products/p399/3.jpg",
   "assets/products/p399/4.jpg",
   "assets/products/p399/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/panerai-luminor-marina-pam00632-handaufzug-2016-full-set"
 },
 {
  "id": "p405",
  "brand": "Breitling",
  "name": "Avenger Bandit Chronograph",
  "ref": "E1338310",
  "price": 3250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2017",
  "size": null,
  "sku": "XN-HR-PRS-WIR2",
  "material": "Titan",
  "dial": "Grau",
  "strap": "Textil",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir den Breitling Avenger Bandit Chronograph im Full Set aus dem Jahr 2017. Die Breitling ist ein kompromisslos sportlicher Chronograph mit 45 mm Titangehäuse, der durch sein geringes Gewicht und extreme Robustheit überzeugt. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p405/0.jpg",
   "assets/products/p405/1.jpg",
   "assets/products/p405/2.jpg",
   "assets/products/p405/3.jpg",
   "assets/products/p405/4.jpg",
   "assets/products/p405/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-bandit-chronograph-e1338310-full-set-jahr-2017"
 },
 {
  "id": "p403",
  "brand": "Omega",
  "name": "Speedmaster Chronoscope",
  "ref": "329.33.43.51.02.001",
  "price": 6250,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Garantiekarte, Box",
  "rating": null,
  "year": null,
  "size": "43 mm",
  "sku": "MG-SPD-CHR",
  "material": "Edelstahl",
  "dial": "Weiß / blau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Omega Speedmaster Chronoscope im Full Set. Die Omega wurde im Frühjahr 2026 im Omega Service Center geprüft und reguliert. (siehe Dokument) Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p403/0.jpg",
   "assets/products/p403/1.jpg",
   "assets/products/p403/2.jpg",
   "assets/products/p403/3.jpg",
   "assets/products/p403/4.jpg",
   "assets/products/p403/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-speedmaster-chronoscope-32933435102001-full-set-jahr-2022"
 },
 {
  "id": "p395",
  "brand": "Omega",
  "name": "Seamaster Aqua Terra GMT",
  "ref": "231.10.43.22.03.001",
  "price": 3950,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "43 mm",
  "sku": "MG-SMS-Q-TRR1",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Leder (guter Zustand)",
  "movement": "Automatik (Manufakturkaliber)",
  "desc": "Hier präsentieren wir die Omega Seamaster Aqua Terra. Für alle, die nicht nur die Zeit im Blick haben, sondern gleich mehrere. Die Omega Aqua Terra hatte im Frühjahr 2025 eine komplette Revision bei einem Uhrmacher erhalten. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p395/0.jpg",
   "assets/products/p395/1.jpg",
   "assets/products/p395/2.jpg",
   "assets/products/p395/3.jpg",
   "assets/products/p395/4.jpg",
   "assets/products/p395/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-aqua-terra-gmt-23110432203001-service-2025"
 },
 {
  "id": "p393",
  "brand": "Rolex",
  "name": "Datejust 41, schwarzes Zifferblatt",
  "ref": "126300",
  "price": 9900,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2026",
  "size": "41 mm",
  "sku": "RLX-DTJ-41-ZB2",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Rolex Datejust 41 aus dem Jahr 2026 im Full Set. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p393/0.jpg",
   "assets/products/p393/1.jpg",
   "assets/products/p393/2.jpg",
   "assets/products/p393/3.jpg",
   "assets/products/p393/4.jpg",
   "assets/products/p393/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-41-zb-black-126300-neu-aus-2026-im-full-set"
 },
 {
  "id": "p367",
  "brand": "IWC",
  "name": "GST Chronograph Titan",
  "ref": "IW370703",
  "price": 2890,
  "listPrice": null,
  "status": "sold",
  "category": "uhren",
  "fullset": null,
  "rating": "Gut",
  "year": null,
  "size": "40 mm",
  "sku": "IWC-GST-CHR-TTN",
  "material": "Titan",
  "dial": "Schwarz",
  "strap": "Titan",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die IWC GST Chronograph aus Titan. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p367/0.jpg",
   "assets/products/p367/1.jpg",
   "assets/products/p367/2.jpg",
   "assets/products/p367/3.jpg",
   "assets/products/p367/4.jpg",
   "assets/products/p367/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-gst-chronograph-titan-iw370703"
 },
 {
  "id": "p382",
  "brand": "Rolex",
  "name": "Datejust 36, schwarzes Zifferblatt",
  "ref": "126200",
  "price": 8950,
  "listPrice": null,
  "status": "sold",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2020",
  "size": "36 mm",
  "sku": "RLX-DTJ-36-ZB",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 ZB schwarz Ref.126200 im Full Set. Lieferzeit 10-14 Tage. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt. Gerne können wir ein Video senden.",
  "images": [
   "assets/products/p382/0.jpg",
   "assets/products/p382/1.jpg",
   "assets/products/p382/2.jpg",
   "assets/products/p382/3.jpg",
   "assets/products/p382/4.jpg",
   "assets/products/p382/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-zb-schwarz-126200-automatik-full-set-jahr-2020"
 },
 {
  "id": "p381",
  "brand": "Rolex",
  "name": "Datejust 36 Edelstahl/Roségold",
  "ref": "126201",
  "price": 12950,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2019",
  "size": "36 mm",
  "sku": "RLX-DTJ-36-DLS",
  "material": "Edelstahl / Roségold",
  "dial": "Grau",
  "strap": "Edelstahl / Roségold",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die Rolex Datejust 36 Ref. 126201 im Full Set. Lieferzeit 10-14 Tage. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt. Gerne können wir ein Video senden.",
  "images": [
   "assets/products/p381/0.jpg",
   "assets/products/p381/1.jpg",
   "assets/products/p381/2.jpg",
   "assets/products/p381/3.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/rolex-datejust-36-edelstahl-rosegold-126201-zb-grau-full-set-2019"
 },
 {
  "id": "p377",
  "brand": "Junghans",
  "name": "Schaltradchronograph Bundeswehr — Unikat",
  "ref": null,
  "price": 4990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": null,
  "year": "1953",
  "size": null,
  "sku": "XN-JNG-SCH-NKT",
  "material": null,
  "dial": null,
  "strap": null,
  "movement": null,
  "desc": "Wir bieten hier ein außergewöhnliches Sammlerstück aus dem Hause Junghans an. Einen seltenen Schaltradchronographen mit militärischem Hintergrund. Dieses Exemplar wurde ursprünglich für die Bundeswehr vorgesehen und zeichnet sich durch mehrere besondere Merkmale aus. Besonders hervorzuheben ist die sogenannte Sternzeitregulierung, die auf eine präzise und hochwertige Feinjustierung des Uhrwerks hinweist.",
  "images": [
   "assets/products/p377/0.jpg",
   "assets/products/p377/1.jpg",
   "assets/products/p377/2.jpg",
   "assets/products/p377/3.jpg",
   "assets/products/p377/4.jpg",
   "assets/products/p377/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--junghans-schaltradchronograph-unikat-fr-die-bundeswehr-mit-dokumenten-deh"
 },
 {
  "id": "p366",
  "brand": "Tag Heuer",
  "name": "Link Chronograph Automatik",
  "ref": "CJF2111",
  "price": 1550,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "42 mm",
  "sku": "TAG-HR-LNK-CHR",
  "material": "Edelstahl",
  "dial": null,
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir den TAG Heuer Link Chronograph. Die TAG Heuer hatte im März 2026 einen kompletten Service erhalten und kommt mit 2x Jahren Garantie. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p366/0.jpg",
   "assets/products/p366/1.jpg",
   "assets/products/p366/2.jpg",
   "assets/products/p366/3.jpg",
   "assets/products/p366/4.jpg",
   "assets/products/p366/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-link-chronograph-automatik-cjf2111-service-032026"
 },
 {
  "id": "p364",
  "brand": "IWC",
  "name": "Pilot’s Watch Chronograph",
  "ref": "IW388102",
  "price": 5550,
  "listPrice": 8600,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2022",
  "size": "41 mm",
  "sku": "IWC-SCH-PLT-CHR",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Manufakturwerk von IWC (Automatik)",
  "desc": "Hier präsentieren den IWC Pilots Chronograph ZB blau im Full Set aus dem Jahr 2022. Der IWC Fliegerchrono hat eine Garantie bis Ende 2030. Der aktuelle Listenpreis liegt bei 8.600 € Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p364/0.jpg",
   "assets/products/p364/1.jpg",
   "assets/products/p364/2.jpg",
   "assets/products/p364/3.jpg",
   "assets/products/p364/4.jpg",
   "assets/products/p364/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-schaffhausen-pilots-chronograph-iw388102-full-set-2022"
 },
 {
  "id": "p347",
  "brand": "Omega",
  "name": "Seamaster Diver 300M „007 Edition“ Titan",
  "ref": "210.92.42.20.01.001",
  "price": 7190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2020",
  "size": "42 mm",
  "sku": "MG-SMS-DVR-300",
  "material": "Titan",
  "dial": "Braun",
  "strap": "Titan",
  "movement": "Automatik (Manufaktur)",
  "desc": "Hier präsentieren wir die Omega Seamaster Diver 300M 007 im Full Set. Diese Seamaster mit einem Durchmesser von 42 mm ist identisch mit der Uhr von 007 in „Keine Zeit zu sterben“, besteht aus robustem und doch leichtem Titan Grade 2 und weist einen Lünettenring sowie ein Zifferblatt aus braunem Aluminium auf. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p347/0.jpg",
   "assets/products/p347/1.jpg",
   "assets/products/p347/2.jpg",
   "assets/products/p347/3.jpg",
   "assets/products/p347/4.jpg",
   "assets/products/p347/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-diver-300m-007-titan-21092422001001-full-set"
 },
 {
  "id": "p352",
  "brand": "Breitling",
  "name": "Avenger Automatik",
  "ref": "A17318101C1A1",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2020",
  "size": "43 mm",
  "sku": "BRT-VNG-TMT-173",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": "Automatik 12",
  "desc": "Hier präsentieren wir die Breitling Avenger ZB blau im Full Set aus dem Jahr 2020. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p352/0.jpg",
   "assets/products/p352/1.jpg",
   "assets/products/p352/2.jpg",
   "assets/products/p352/3.jpg",
   "assets/products/p352/4.jpg",
   "assets/products/p352/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-avenger-automatik-a17318101c1a1-full-set-jahr-2020"
 },
 {
  "id": "p357",
  "brand": "IWC",
  "name": "Portofino 37 Automatic Diamond Dial",
  "ref": "IW458101",
  "price": 3190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Garantiekarte, Box",
  "rating": null,
  "year": "2021",
  "size": "37 mm",
  "sku": "IWC-PRT-37-TMT",
  "material": "Edelstahl",
  "dial": "Silber",
  "strap": "Leder",
  "movement": "Automatik 12",
  "desc": "Hier präsentieren wir die IWC Portofino 37 aus dem Jahr 2021 im Full Set mit einer Restgarantie bei IWC bis 2029. Unsere Bilder sind unbearbeitet und zeigen jedes Detail, mehr als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p357/0.jpg",
   "assets/products/p357/1.jpg",
   "assets/products/p357/2.jpg",
   "assets/products/p357/3.jpg",
   "assets/products/p357/4.jpg",
   "assets/products/p357/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-portofino-37-automatic-iw458101-silber-dia-dial-2021-full-set"
 },
 {
  "id": "p350",
  "brand": "Tag Heuer",
  "name": "Carrera Calibre 16 Chronograph",
  "ref": "CBM2110.BA065",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": "41 mm",
  "sku": "TAG-HR-CRR-CLB2",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": "Automatik",
  "desc": "Hier präsentieren wir die TAG Heuer Carrera Calibre 16. Der Listenpreis der Tag Heuer liegt bei 5.800 Euro in Deutschland. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p350/0.jpg",
   "assets/products/p350/1.jpg",
   "assets/products/p350/2.jpg",
   "assets/products/p350/3.jpg",
   "assets/products/p350/4.jpg",
   "assets/products/p350/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-calibre-16-cbm2110ba065-chronograph"
 },
 {
  "id": "p335",
  "brand": "Breitling",
  "name": "Chronomat Burgundy Dial",
  "ref": "B13047",
  "price": 2190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Echtheitszertifikat",
  "rating": "Gut",
  "year": null,
  "size": "39 mm",
  "sku": "BRT-CHR-B13-BRG",
  "material": "Edelstahl",
  "dial": "Burgundy Dial",
  "strap": "Leder",
  "movement": null,
  "desc": "Hier präsentieren wir die Breitling Chronomat in Stahl/Gold mit Echtheitszertifikat. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Gut erkennbar Glas: Sehr gut Lünette: Gut erkennbar Armband: Sehr gut Schließe: Sehr gut (After market, siehe Bilder) Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p335/0.jpg",
   "assets/products/p335/1.jpg",
   "assets/products/p335/2.jpg",
   "assets/products/p335/3.jpg",
   "assets/products/p335/4.jpg",
   "assets/products/p335/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/breitling-chronomat-b13047-burgundy-dial-mit-echtheitszertifikat"
 },
 {
  "id": "p334",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean 45 mm",
  "ref": "2200.50.00",
  "price": 2990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Box",
  "rating": "Sehr gut",
  "year": null,
  "size": "45 mm",
  "sku": "MG-SMS-PLN-CN1",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Planet Ocean mit original Omegabox. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut Gehäuse: Sehr gut Glas: Gut Lünette: Sehr gut Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p334/0.jpg",
   "assets/products/p334/1.jpg",
   "assets/products/p334/2.jpg",
   "assets/products/p334/3.jpg",
   "assets/products/p334/4.jpg",
   "assets/products/p334/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-seamaster-planet-ocean-45-mm-22005000-uhrenbox"
 },
 {
  "id": "p332",
  "brand": "Tag Heuer",
  "name": "Carrera Calibre 16",
  "ref": "CV2010",
  "price": 1650,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2011",
  "size": "41 mm",
  "sku": "TAG-HR-CRR-CLB1",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Tag Heuer Carrera Chronograph aus dem Jahr 2011 im Full Set. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Sehr gut Glas: Gut Lünette: Gut Armband: Gut Schließe: Gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p332/0.jpg",
   "assets/products/p332/1.jpg",
   "assets/products/p332/2.jpg",
   "assets/products/p332/3.jpg",
   "assets/products/p332/4.jpg",
   "assets/products/p332/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-calibre-16-cv2010-full-set-automatik-jahr-2011"
 },
 {
  "id": "p246",
  "brand": "Tag Heuer",
  "name": "Carrera Chronograph",
  "ref": "CV2010",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2007",
  "size": "41 mm",
  "sku": "TAG-HR-CRR-CHR1",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Tag Heuer Carrera. Diese Tag Heuer hatte im November 2025 eine komplette Revision erhalten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut / gut Gehäuse: Sehr gut Glas: Sehr gut Lünette: Sehr gut (Lünette Pos. 3-4 Schlag) Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p246/0.jpg",
   "assets/products/p246/1.jpg",
   "assets/products/p246/2.jpg",
   "assets/products/p246/3.jpg",
   "assets/products/p246/4.jpg",
   "assets/products/p246/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-chronograph-ref-cv2010-service-2025-full-set"
 },
 {
  "id": "p304",
  "brand": "Nomos",
  "name": "Club Neomatik „175 Years“ Weltzeit",
  "ref": null,
  "price": 4990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": null,
  "year": "2025",
  "size": null,
  "sku": "NMS-CLB-NMT-WLT",
  "material": "Edelstahl -",
  "dial": "Champagner -",
  "strap": "Leder -",
  "movement": null,
  "desc": "Hier präsentieren wir die Nomos Club Sport 40 neomatik Weltzeit Roam aus dem Jahr 2025 im Full Set. Alle wichtigen Details auf einen Blick: - Gesamtbewertung: Sehr gut (99% wie neu) - Gehäuse: Sehr gut - Glas: Sehr gut - Lünette: Sehr gut - Armband: Sehr gut - Schließe: Sehr gut - Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p304/0.jpg",
   "assets/products/p304/1.jpg",
   "assets/products/p304/2.jpg",
   "assets/products/p304/3.jpg",
   "assets/products/p304/4.jpg",
   "assets/products/p304/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/nomos-club-neomatik-weltzeit-175-limited-99-neu"
 },
 {
  "id": "p298",
  "brand": "Tag Heuer",
  "name": "Carrera Chronograph",
  "ref": "CV2010",
  "price": 1590,
  "listPrice": null,
  "status": "sold",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut -",
  "year": "2008",
  "size": "41 mm",
  "sku": "TAG-HR-CRR-CHR",
  "material": "Edelstahl -",
  "dial": "Schwarz -",
  "strap": "Edelstahl -",
  "movement": null,
  "desc": "Hier präsentieren wir die Tag Heuer Carrera Chronograph aus dem Jahr 2008 im Full Set. Alle wichtigen Details auf einen Blick: - Gesamtbewertung: Gut - Gehäuse: Sehr gut - Glas: Vorne (Sehr gut)/ Hinten Kratzer auf den Saphirglasboden - Lünette: Auffällig (siehe Bilder) - Armband: Sehr gut - Schließe: Sehr gut - Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p298/0.jpg",
   "assets/products/p298/1.jpg",
   "assets/products/p298/2.jpg",
   "assets/products/p298/3.jpg",
   "assets/products/p298/4.jpg",
   "assets/products/p298/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-chronograph-refcv2010-aus-2008-im-full-set"
 },
 {
  "id": "p300",
  "brand": "Hublot",
  "name": "Faltschließe 18 K Rotgold · 20 mm",
  "ref": null,
  "price": 2290,
  "listPrice": null,
  "status": "available",
  "category": "zubehoer",
  "fullset": null,
  "rating": null,
  "year": null,
  "size": "20 mm",
  "sku": "XN-HBL-FLT-AUS",
  "material": null,
  "dial": null,
  "strap": null,
  "movement": null,
  "desc": "Wir bieten hier eine originale Hublot Faltschließe aus 18k Rotgold an. Bandanstoß: 20 mm. Bei weiteren Fragen stehen wir jederzeit zur Verfügung.",
  "images": [
   "assets/products/p300/0.jpg",
   "assets/products/p300/1.jpg",
   "assets/products/p300/2.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/xn--hublot-faltschliee-aus-18-karat-rotgold-fr-20-mm-bandansto-wue5b97l"
 },
 {
  "id": "p292",
  "brand": "IWC",
  "name": "Fliegerchronograph Automatik ZB Schwarz",
  "ref": "IW377701",
  "price": 3290,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Gut",
  "year": "2014",
  "size": "43 mm",
  "sku": "IWC-FLG-W37-TMT",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir eine wahre Ikone von IWC Schaffhausen — den IWC Flieger Chronograph. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Gut Glas: Sehr gut Lünette: Gut Armband: Gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p292/0.jpg",
   "assets/products/p292/1.jpg",
   "assets/products/p292/2.jpg",
   "assets/products/p292/3.jpg",
   "assets/products/p292/4.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/iwc-fliegerchronograph-iw377701-automatik-zb-schwarz"
 },
 {
  "id": "p283",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean 43,5 mm",
  "ref": "215.30.44.21.03.001",
  "price": 4190,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2018",
  "size": "43,5 mm",
  "sku": "MG-PLN-CN-43",
  "material": "Edelstahl",
  "dial": "Blau",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir Omega Planet Ocean im Full Set. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut Gehäuse: Sehr gut Glas: Gut Lünette: Sehr gut Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p283/0.jpg",
   "assets/products/p283/1.jpg",
   "assets/products/p283/2.jpg",
   "assets/products/p283/3.jpg",
   "assets/products/p283/4.jpg",
   "assets/products/p283/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-435-mm-ref-21530442103001-full-set-2018"
 },
 {
  "id": "p263",
  "brand": "Tag Heuer",
  "name": "Carrera GMT Big Date",
  "ref": "WAR201Z",
  "price": 1890,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": null,
  "rating": "Sehr gut",
  "year": null,
  "size": null,
  "sku": "TAG-HR-CRR-GMT",
  "material": "Edelstahl",
  "dial": "Grau",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir den Tag Heuer Carrera GMT Big Date. Diese Tag Heuer hatte im November 2025 eine komplette Revision erhalten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Sehr gut Gehäuse: Sehr gut Glas: Sehr gut Lünette: Sehr gut Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p263/0.jpg",
   "assets/products/p263/1.jpg",
   "assets/products/p263/2.jpg",
   "assets/products/p263/3.jpg",
   "assets/products/p263/4.jpg",
   "assets/products/p263/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/tag-heuer-carrera-gmt-big-date-ref-war201z-service-nov-2025"
 },
 {
  "id": "p223",
  "brand": "Omega",
  "name": "Seamaster Planet Ocean",
  "ref": "2201.51.00",
  "price": 3390,
  "listPrice": null,
  "status": "sold",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Gut",
  "year": "2009",
  "size": "42 mm",
  "sku": "MG-PLN-CN-REF",
  "material": "Edelstahl",
  "dial": "Schwarz",
  "strap": "Edelstahl",
  "movement": null,
  "desc": "Hier präsentieren wir die Omega Planet Ocean 42 mit orange Akzenten. Alle wichtigen Details auf einen Blick: Gesamtbewertung: Gut Gehäuse: Sehr gut Glas: Gut (Mikrokratzer, siehe Bilder) Lünette: In Ordnung (leichte Kratzer auf der Pos., 3-5 siehe Bilder) Armband: Sehr gut Schließe: Sehr gut Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p223/0.jpg",
   "assets/products/p223/1.jpg",
   "assets/products/p223/2.jpg",
   "assets/products/p223/3.jpg",
   "assets/products/p223/4.jpg",
   "assets/products/p223/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/omega-planet-ocean-ref22015100-aus-2009-im-full-set"
 },
 {
  "id": "p185",
  "brand": "Bvlgari",
  "name": "Octo Finissimo Chronograph GMT",
  "ref": null,
  "price": 11990,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut",
  "year": "2022",
  "size": "42 mm",
  "sku": "BVL-CT-FNS-CHR",
  "material": "Titan",
  "dial": "Grau",
  "strap": "Titan",
  "movement": null,
  "desc": "Hier präsentieren wir die Bulgari Octo Finissimo Chronograph GMT aus dem Jahr 2022 im Full Set. Die Octo Finissimo Chronograph GMT bietet die perfekte Mischung aus technischer Raffinesse und ästhetischer Eleganz. Als flachste Automatikuhr der Welt, die mit Chronograph und GMT-Funktion ausgestattet ist.",
  "images": [
   "assets/products/p185/3.jpg",
   "assets/products/p185/2.jpg",
   "assets/products/p185/0.jpg",
   "assets/products/p185/1.jpg",
   "assets/products/p185/4.jpg",
   "assets/products/p185/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/bvlgari-octo-finissimo-chronograph-gmt-jahr-2022-full-set"
 },
 {
  "id": "p180",
  "brand": "Montblanc",
  "name": "TimeWalker 43 mm",
  "ref": "118488",
  "price": 2090,
  "listPrice": null,
  "status": "available",
  "category": "uhren",
  "fullset": "Full Set, Papiere, Box",
  "rating": "Sehr gut -",
  "year": "2017",
  "size": "43 mm",
  "sku": "MNT-TMW-43M-REF",
  "material": "Edelstahl -",
  "dial": "Silber -",
  "strap": "Edelstahl -",
  "movement": null,
  "desc": "Hier präsentieren wir die Montblanc Timewalker aus dem Jahr 2017 im Full Set. Alle wichtigen Details auf einen Blick: - Gesamtbewertung: Sehr gut - Gehäuse: Sehr gut - Glas: Sehr gut - Lünette: Sehr gut - Armband: Sehr gut - Schließe: Sehr gut - Uhrwerk: Geprüft auf einwandfreies Laufverhalten, kein anstehender Service. Unsere Bilder sind unbearbeitet und zeigen jedes Detail — mehr, als das bloße Auge wahrnimmt.",
  "images": [
   "assets/products/p180/0.jpg",
   "assets/products/p180/1.jpg",
   "assets/products/p180/2.jpg",
   "assets/products/p180/3.jpg",
   "assets/products/p180/4.jpg",
   "assets/products/p180/5.jpg"
  ],
  "sourceUrl": "https://hahn-vo.de/shop/ols/products/montblanc-timewalker-43mm-ref-118488-aus-2017-im-full-set"
 }
];

window.FLAGSHIP_ID = "p462";
window.NEW_IN = ["p462", "p461", "p460", "p459", "p458", "p457"];

window.TESTIMONIALS = [
 {
  "name": "Sebastian K.",
  "date": "Juni 2026",
  "watch": "Omega Speedmaster 38",
  "img": "assets/products/p457/0.jpg",
  "text": "Der Zustand war exakt wie beschrieben, eher besser. Die Übergabe im Showroom über den Dächern des Bankenviertels ist ein Erlebnis für sich."
 },
 {
  "name": "Daniel R.",
  "date": "Mai 2026",
  "watch": "Rolex Datejust 41",
  "img": "assets/products/p444/0.jpg",
  "text": "Sehr transparente Beratung, kein Verkaufsdruck. Die Uhr wurde vor meinen Augen geöffnet und geprüft. So stellt man sich den Kauf einer Luxusuhr vor."
 },
 {
  "name": "Tobias N.",
  "date": "April 2026",
  "watch": "Tudor Black Bay 41",
  "img": "assets/products/p413/0.jpg",
  "text": "Suchauftrag abgegeben, drei Wochen später kam das Angebot. Besserer Zustand und besserer Preis als alles, was ich selbst gefunden hatte."
 },
 {
  "name": "Alexandra B.",
  "date": "März 2026",
  "watch": "IWC Portofino 37",
  "img": "assets/products/p357/0.jpg",
  "text": "Meine alte Uhr wurde fair in Zahlung genommen, die Differenz war nach zwei Tagen auf dem Konto. Abwicklung komplett unkompliziert."
 },
 {
  "name": "Jonas W.",
  "date": "Februar 2026",
  "watch": "Breitling Navitimer B01",
  "img": "assets/products/p415/0.jpg",
  "text": "Versicherter Versand, doppelt verpackt, mit frischem Servicenachweis. Kommunikation per WhatsApp innerhalb von Minuten. Absolute Empfehlung."
 },
 {
  "name": "Martin H.",
  "date": "Januar 2026",
  "watch": "Rolex Submariner Date",
  "img": "assets/products/p452/0.jpg",
  "text": "Ich habe lange verglichen. Hier stimmte am Ende alles: Full Set, nachvollziehbare Historie und ein Preis, der sich am Markt belegen ließ."
 },
 {
  "name": "Christina L.",
  "date": "Dezember 2025",
  "watch": "Cartier Clé de Cartier",
  "img": "assets/products/p439/0.jpg",
  "text": "Ein Weihnachtsgeschenk für meinen Mann. Ich hatte wenig Ahnung von Uhren, wurde aber geduldig und ehrlich beraten. Er trägt sie jeden Tag."
 },
 {
  "name": "Stephan F.",
  "date": "November 2025",
  "watch": "Glashütte Original PanoMaticLunar",
  "img": "assets/products/p456/0.jpg",
  "text": "Selten so ein gepflegtes Exemplar gesehen. Auf Nachfrage bekam ich sofort Makroaufnahmen von jedem Detail, sogar vom Werk."
 },
 {
  "name": "Erik P.",
  "date": "November 2025",
  "watch": "Sinn 103",
  "img": "assets/products/p451/0.jpg",
  "text": "Kleiner Preis, gleiche Sorgfalt: Auch bei einer Uhr unter 2.500 Euro wurde geöffnet, geprüft und dokumentiert. Das nenne ich Standards."
 },
 {
  "name": "Nadja S.",
  "date": "Oktober 2025",
  "watch": "Nomos Ludwig",
  "img": "assets/products/p434/0.jpg",
  "text": "Schnelle Antwort, ehrliche Zustandsbeschreibung, sicherer Versand nach Berlin. Die Uhr kam schöner an, als die Fotos versprochen hatten."
 },
 {
  "name": "Michael T.",
  "date": "September 2025",
  "watch": "Omega Seamaster 007 Edition",
  "img": "assets/products/p347/0.jpg",
  "text": "Termin am Samstagabend, eine Stunde Zeit, drei Uhren anprobiert. Am Ende wurde es die Seamaster. Keine Sekunde bereut."
 },
 {
  "name": "Kerstin M.",
  "date": "September 2025",
  "watch": "Jaeger-LeCoultre Reverso",
  "img": "assets/products/p446/0.jpg",
  "text": "Eine Vintage-Uhr kauft man nicht ohne Vertrauen. Hier wurde mir jede Frage zur Historie beantwortet, inklusive Servicebelegen."
 },
 {
  "name": "Oliver B.",
  "date": "August 2025",
  "watch": "TAG Heuer Carrera",
  "img": "assets/products/p350/0.jpg",
  "text": "Meine erste Automatikuhr. Statt mir die teuerste zu verkaufen, wurde mir die passendste empfohlen. Genau deshalb komme ich wieder."
 },
 {
  "name": "Patrick S.",
  "date": "Juli 2025",
  "watch": "Omega Planet Ocean",
  "img": "assets/products/p384/0.jpg",
  "text": "Werttransport nach München, versichert und mit Sendungsverfolgung. Zwei Tage später war die Uhr am Handgelenk. Reibungslos."
 },
 {
  "name": "Julia V.",
  "date": "Juni 2025",
  "watch": "Rolex Datejust 36",
  "img": "assets/products/p458/0.jpg",
  "text": "Das blaue Blatt sah auf den Fotos schon gut aus, in echt ist es noch besser. Danke für die ehrliche Einordnung zum Marktpreis."
 },
 {
  "name": "Andreas G.",
  "date": "Mai 2025",
  "watch": "IWC Big Pilot Top Gun",
  "img": "assets/products/p454/0.jpg",
  "text": "Zwei Jahre nach einer bestimmten Keramik-Referenz gesucht. Über das Netzwerk nach Seoul wurde sie in sechs Wochen gefunden. Stark."
 },
 {
  "name": "Robert K.",
  "date": "April 2025",
  "watch": "Breitling Superocean Héritage",
  "img": "assets/products/p438/0.jpg",
  "text": "Fairer Ankaufspreis für meine alte Uhr, sofortige Überweisung nach der Prüfung. Beim nächsten Kauf führt kein Weg an Frankfurt vorbei."
 },
 {
  "name": "Sandra W.",
  "date": "April 2025",
  "watch": "Cartier Tank Solo",
  "img": "assets/products/p461/0.jpg",
  "text": "Unkomplizierter geht es nicht: abends angefragt, morgens Antwort, drei Tage später Übergabe im Showroom mit Kaffee und Zeit."
 },
 {
  "name": "Frank D.",
  "date": "März 2025",
  "watch": "Omega Speedmaster Chronoscope",
  "img": "assets/products/p403/0.jpg",
  "text": "Als Sammler achte ich auf Kleinigkeiten. Hier stimmten Zwischenglieder, Plomben und Papiere. Ein Händler, der sein Handwerk gelernt hat."
 },
 {
  "name": "Lukas E.",
  "date": "Februar 2025",
  "watch": "Tudor Royal 34",
  "img": "assets/products/p427/0.jpg",
  "text": "Ein Geschenk zum Jahrestag, pünktlich und wunderschön verpackt geliefert. Meine Frau war sprachlos. Vielen Dank nach Frankfurt!"
 }
];

window.FAQ = [
 {
  "q": "Sind alle Uhren auf Echtheit geprüft?",
  "a": "Ja. Jede Uhr wird vor dem Verkauf von uns geöffnet, das Werk kontrolliert und mit Referenz- und Seriennummer dokumentiert. Beide Gründer haben ihr Handwerk bei Bucherer gelernt — wir kaufen keine Uhr an, die wir nicht selbst geprüft haben."
 },
 {
  "q": "Welche Garantie erhalte ich?",
  "a": "Auf jede Uhr geben wir 12 Monate Garantie auf das Werk — zusätzlich zu einer eventuell noch laufenden Herstellergarantie. Viele unserer Uhren kommen zudem mit frischem Servicenachweis."
 },
 {
  "q": "Kann ich eine Uhr zurückgeben?",
  "a": "Ja, Sie haben 14 Tage Rückgaberecht. Die Uhr muss sich im gelieferten Zustand befinden, inklusive aller Plomben, Papiere und Zubehörteile."
 },
 {
  "q": "Wie läuft die Übergabe ab?",
  "a": "Wahlweise per weltweit vollversichertem Wertversand oder — unsere Empfehlung — persönlich in unserem Showroom im Garden Tower, 7. Etage, im Frankfurter Bankenviertel. Termine vereinbaren Sie in Minuten per WhatsApp oder E-Mail."
 },
 {
  "q": "Nehmen Sie meine Uhr in Zahlung?",
  "a": "Sehr gern. Senden Sie uns über die Ankauf-Seite Fotos und Eckdaten Ihrer Uhr — Sie erhalten innerhalb von 24–48 Stunden ein konkretes Angebot, das Sie direkt mit einem Kauf verrechnen können."
 },
 {
  "q": "Ich suche eine bestimmte Uhr. Können Sie sie beschaffen?",
  "a": "Das ist eine unserer Stärken. Über unser Netzwerk — unter anderem nach Südkorea und Japan — finden wir Referenzen, die auf dem europäischen Markt kaum zu bekommen sind. Stellen Sie einfach einen Suchauftrag."
 }
];
